// Lügnerjagd – Fragenkategorien
// Mehrheit bekommt Frage A, einer bekommt Frage B (die "Lügner-Frage")
// Die Runde diskutiert wer anders geantwortet hat / wer lügt

export type LuegnerjagdCategory =
  | "filme" | "musik" | "fussball" | "alltag" | "essen"
  | "urlaub" | "freundschaft" | "arbeit" | "liebe" | "kindheit"
  | "getraenke" | "party" | "soziales" | "tech" | "sport"
  | "geld" | "schule" | "natur" | "wildcard";

export interface LuegnerjagdQuestion {
  id: number;
  category: LuegnerjagdCategory;
  majority: string;   // Frage für alle außer dem Lügner
  liar: string;       // Frage nur für den Lügner
  hint?: string;      // Tipp für die Moderation
}

export const LUEGNERJAGD_QUESTIONS: LuegnerjagdQuestion[] = [

  // ── FILME ─────────────────────────────────────────────────────────────────
  { id: 1, category: "filme",
    majority: "Welcher Film hat dich zum Weinen gebracht?",
    liar: "Welcher Film lässt dich komplett kalt, obwohl alle anderen weinen?",
    hint: "Achte auf Zögern – wer keinen echten Gänsehaut-Moment hatte." },
  { id: 2, category: "filme",
    majority: "Welcher Film hast du mindestens dreimal gesehen?",
    liar: "Welchen Film hast du angefangen und nie zu Ende geschaut?" },
  { id: 3, category: "filme",
    majority: "Welcher Schauspieler oder welche Schauspielerin findest du unglaublich talentiert?",
    liar: "Welchen Star findest du hoffnungslos überbewertet?" },
  { id: 4, category: "filme",
    majority: "Was war dein Lieblingsfilm als Kind?",
    liar: "Welchen Kinderfilm fandst du als Kind schrecklich langweilig?" },
  { id: 5, category: "filme",
    majority: "Welche Serie hast du in einem Rutsch durchgeschaut?",
    liar: "Welche gehypte Serie hast du nach einer Folge abgebrochen?" },
  { id: 6, category: "filme",
    majority: "Welcher Filmklassiker ist für dich absolut zeitlos?",
    liar: "Welchen Filmklassiker findest du heimlich total langweilig?" },
  { id: 7, category: "filme",
    majority: "Welches Filmende hat dich wirklich überrascht?",
    liar: "Welches 'große' Filmende hast du schon von weitem kommen sehen?" },
  { id: 8, category: "filme",
    majority: "Welchen Film würdest du jedem empfehlen?",
    liar: "Welchen Film hast du empfohlen, obwohl du ihn gar nicht gut fandest?" },
  { id: 9, category: "filme",
    majority: "In welchem Film-Universum würdest du am liebsten leben?",
    liar: "In welchem Film-Universum wärst du der Erste, der stirbt?" },
  { id: 10, category: "filme",
    majority: "Welcher Horrorfilm hat dir wirklich Angst gemacht?",
    liar: "Welchen Horrorfilm fandst du eher zum Lachen als gruselig?" },

  // ── MUSIK ─────────────────────────────────────────────────────────────────
  { id: 11, category: "musik",
    majority: "Welches Lied läuft bei dir immer wieder, egal wie oft du es gehört hast?",
    liar: "Welches Lied, das alle lieben, nervt dich nach 10 Sekunden?" },
  { id: 12, category: "musik",
    majority: "Welcher Song begleitet dich auf langen Autofahrten?",
    liar: "Bei welchem Song drehst du das Radio sofort ab?" },
  { id: 13, category: "musik",
    majority: "Welcher Künstler oder welche Band war dein absolutes Ding in der Jugend?",
    liar: "Wessen Musik kannst du bis heute nicht ausstehen, obwohl alle deine Freunde sie liebten?" },
  { id: 14, category: "musik",
    majority: "Welches Konzert war das beste deines Lebens?",
    liar: "Bei welchem Konzert warst du und hättest lieber Zuhause bleiben sollen?" },
  { id: 15, category: "musik",
    majority: "Was ist dein Guilty-Pleasure-Song – den du heimlich liebst?",
    liar: "Was ist ein Song, den du in der Öffentlichkeit gerne hörst, aber niemals zugibst?" },
  { id: 16, category: "musik",
    majority: "Welcher Song bringt dich sofort in Partystimmung?",
    liar: "Welcher Partysong macht dich eher müde als wach?" },
  { id: 17, category: "musik",
    majority: "Welches Musikgenre hörst du am häufigsten?",
    liar: "Welches Musikgenre verstehst du überhaupt nicht, obwohl alle es feiern?" },
  { id: 18, category: "musik",
    majority: "Was war das erste Album oder der erste Song, den du dir selbst gekauft hast?",
    liar: "Welches damals coole Album liegt heute schamvoll in deiner Vergangenheit?" },

  // ── FUSSBALL ──────────────────────────────────────────────────────────────
  { id: 19, category: "fussball",
    majority: "Welches Fußballspiel wirst du nie vergessen?",
    liar: "Welches angeblich 'legendäre' Spiel fandst du eigentlich langweilig?" },
  { id: 20, category: "fussball",
    majority: "Wer ist für dich der beste Spieler aller Zeiten?",
    liar: "Welchen als 'GOAT' gefeierten Spieler findest du überschätzt?" },
  { id: 21, category: "fussball",
    majority: "Für welchen Verein drückst du die Daumen, wenn du keine eigene Mannschaft hast?",
    liar: "Welchen Verein kannst du einfach nicht leiden, egal was?" },
  { id: 22, category: "fussball",
    majority: "Welcher Torjubel oder welche Szene hat dich vom Sofa gerissen?",
    liar: "Welchen Torjubel hast du mitgemacht, obwohl du innerlich gleichgültig warst?" },
  { id: 23, category: "fussball",
    majority: "Welcher Trainer hat einen Verein wirklich geprägt?",
    liar: "Welchem Trainer wird viel zu viel Kredit gegeben, obwohl die Spieler mehr dazu beitragen?" },
  { id: 24, category: "fussball",
    majority: "Was war dein persönlicher Fußball-Tiefpunkt als Fan?",
    liar: "Welche angebliche Fan-Niederlage hat dich heimlich kalt gelassen?" },
  { id: 25, category: "fussball",
    majority: "Welches Land spielte bei einer WM oder EM richtig guten Fußball?",
    liar: "Welches Land wurde bei einem Turnier unfair hochgejubelt?" },
  { id: 26, category: "fussball",
    majority: "Wer war dein Lieblingsspieler als Kind?",
    liar: "Welchem Spieler bist du früher nachgelaufen, den du heute peinlich findest?" },

  // ── ALLTAG ────────────────────────────────────────────────────────────────
  { id: 27, category: "alltag",
    majority: "Was ist dein Morgenritual, das du nie auslässt?",
    liar: "Was solltest du jeden Morgen tun, tust es aber so gut wie nie?" },
  { id: 28, category: "alltag",
    majority: "Welche App nutzt du täglich am meisten?",
    liar: "Welche App hast du installiert und nie wieder geöffnet?" },
  { id: 29, category: "alltag",
    majority: "Was machst du als Erstes, wenn du Zuhause ankommst?",
    liar: "Was solltest du als Erstes tun, machst es aber grundsätzlich zuletzt?" },
  { id: 30, category: "alltag",
    majority: "Wie viel Zeit verbringst du täglich wirklich mit dem Handy?",
    liar: "Wie sehr unterschätzt du deinen echten Handykonsum?" },
  { id: 31, category: "alltag",
    majority: "Was erledigst du immer sofort, wenn es auftaucht?",
    liar: "Was schiebst du solange auf, bis es nicht mehr ignoriert werden kann?" },
  { id: 32, category: "alltag",
    majority: "Wann gehst du normalerweise schlafen?",
    liar: "Wie oft bleibst du viel länger auf als geplant, obwohl du früh aufstehen musst?" },
  { id: 33, category: "alltag",
    majority: "Was ist dein Lieblingsplatz, um sich nach einem langen Tag zu entspannen?",
    liar: "Was tust du zur 'Entspannung', das dich eigentlich noch müder macht?" },
  { id: 34, category: "alltag",
    majority: "Welche Routine gibt dir Energie für den Tag?",
    liar: "Was hast du dir als gesunde Routine vorgenommen, aber nach einer Woche aufgehört?" },
  { id: 35, category: "alltag",
    majority: "Wie trinkst du deinen Kaffee oder Tee am liebsten?",
    liar: "Was trinkst du nur, um wach zu bleiben, obwohl du es eigentlich nicht magst?" },
  { id: 36, category: "alltag",
    majority: "Was kaufst du immer spontan, obwohl du es gar nicht brauchst?",
    liar: "Was hast du gekauft und versteckt, damit niemand fragt, warum du das hast?" },

  // ── ESSEN ─────────────────────────────────────────────────────────────────
  { id: 37, category: "essen",
    majority: "Was ist dein absolutes Lieblingsessen, das du immer wählen würdest?",
    liar: "Was isst du nur, damit es niemand merkt, dass du wählerisch bist?" },
  { id: 38, category: "essen",
    majority: "Welches Gericht würdest du jedem empfehlen, der deine Stadt besucht?",
    liar: "Was ist ein lokales 'Muss' das du heimlich nicht ausstehen kannst?" },
  { id: 39, category: "essen",
    majority: "Was kochst du, wenn du beeindrucken willst?",
    liar: "Was hast du mal als selbst gekocht ausgegeben, das du heimlich bestellt hattest?" },
  { id: 40, category: "essen",
    majority: "Was isst du, wenn du Stress hast oder traurig bist?",
    liar: "Was isst du, das du niemandem gestehst, weil es so ungesund ist?" },
  { id: 41, category: "essen",
    majority: "Welches Essen macht dich sofort glücklich?",
    liar: "Welches Essen findest du überschätzt, obwohl alle davon schwärmen?" },
  { id: 42, category: "essen",
    majority: "Was war das beste Essen, das du je in einem Restaurant hattest?",
    liar: "Wofür hast du zu viel Geld in einem Restaurant bezahlt und warst enttäuscht?" },
  { id: 43, category: "essen",
    majority: "Was ist dein Ritual wenn du Fast Food bestellst?",
    liar: "Was bestellst du heimlich, wenn du allein bist – das du nie vor anderen essen würdest?" },
  { id: 44, category: "essen",
    majority: "Welche Küche der Welt könntest du jeden Tag essen?",
    liar: "Welche hochgelobte Küche findest du eigentlich ziemlich unspektakulär?" },

  // ── URLAUB ────────────────────────────────────────────────────────────────
  { id: 45, category: "urlaub",
    majority: "Welches Reiseziel hat dich wirklich begeistert?",
    liar: "Wohin bist du gereist, weil alle anderen es toll fanden – und du warst enttäuscht?" },
  { id: 46, category: "urlaub",
    majority: "Was packst du immer zuerst, wenn du einen Koffer packst?",
    liar: "Was hast du mal vergessen einzupacken und bereust es bis heute?" },
  { id: 47, category: "urlaub",
    majority: "Was ist dein liebstes Urlaubsritual – etwas das du immer machst?",
    liar: "Was machst du im Urlaub nur für Instagram, das dir eigentlich keinen Spaß macht?" },
  { id: 48, category: "urlaub",
    majority: "Welches Land steht ganz oben auf deiner Bucket List?",
    liar: "Welches 'traumhafte' Reiseziel hat dich nach einem Besuch komplett kalt gelassen?" },
  { id: 49, category: "urlaub",
    majority: "Was ist dein Lieblingstransportmittel auf Reisen?",
    liar: "Was ist ein Transportmittel, das du nie wieder benutzen würdest?" },
  { id: 50, category: "urlaub",
    majority: "Was ist eine Reiseerinnerung, die du nie vergisst?",
    liar: "Was war eine Reise, bei der eigentlich alles schiefging?" },

  // ── FREUNDSCHAFT ──────────────────────────────────────────────────────────
  { id: 51, category: "freundschaft",
    majority: "Was würdest du für einen guten Freund tun, das für andere verrückt klingt?",
    liar: "Was haben Freunde für dich getan, wofür du dich heimlich immer noch schämst?" },
  { id: 52, category: "freundschaft",
    majority: "Was ist das Wichtigste, das du an einem guten Freund schätzt?",
    liar: "Was ist eine Eigenschaft, die du bei Freunden heimlich nervt, die du aber nie ansprichst?" },
  { id: 53, category: "freundschaft",
    majority: "Wie lange kennst du deinen ältesten Freund oder deine älteste Freundin?",
    liar: "Mit wem aus deinem Freundeskreis hast du eigentlich wenig gemeinsam?" },
  { id: 54, category: "freundschaft",
    majority: "Was ist eine Tradition mit Freunden, die du immer pflegst?",
    liar: "Was machst du mit Freunden nur aus Pflichtgefühl und nicht weil du wirklich Lust hast?" },
  { id: 55, category: "freundschaft",
    majority: "Was ist das verrücktste, das du mit Freunden erlebt hast?",
    liar: "Was hast du mit Freunden mitgemacht, das du eigentlich gar nicht wolltest?" },

  // ── ARBEIT ────────────────────────────────────────────────────────────────
  { id: 56, category: "arbeit",
    majority: "Was ist deine heimliche Superkraft bei der Arbeit?",
    liar: "Was gibt du als Stärke aus, das eigentlich eher eine Schwäche ist?" },
  { id: 57, category: "arbeit",
    majority: "Was macht dir bei deiner Arbeit oder deinem Studium am meisten Spaß?",
    liar: "Was tust du täglich bei der Arbeit und findest es heimlich sinnlos?" },
  { id: 58, category: "arbeit",
    majority: "Wie überbrückst du einen langweiligen Arbeitstag?",
    liar: "Was tust du im Homeoffice, das dein Vorgesetzter niemals wissen darf?" },
  { id: 59, category: "arbeit",
    majority: "Was ist ein Skill, den du dir gerne aneignen würdest?",
    liar: "Was hast du im Lebenslauf stehen, das du nicht wirklich kannst?" },
  { id: 60, category: "arbeit",
    majority: "Was ist das Beste an einem Feierabend nach einem langen Tag?",
    liar: "Was sagst du am Feierabend immer – und tust es dann doch nicht?" },

  // ── LIEBE ─────────────────────────────────────────────────────────────────
  { id: 61, category: "liebe",
    majority: "Was ist die romantischste Geste, die du je erlebt oder gemacht hast?",
    liar: "Was gilt als romantisch, findest du aber eigentlich total übertrieben?" },
  { id: 62, category: "liebe",
    majority: "Was ist für dich ein absolutes No-Go auf einem ersten Date?",
    liar: "Was hast du auf einem Date selbst getan, was du eigentlich ablehnen würdest?" },
  { id: 63, category: "liebe",
    majority: "Was ist dein Lieblingsweg, um jemandem zu zeigen, dass du ihn magst?",
    liar: "Was tust du in Beziehungen nur um des Friedens willen, obwohl du es hasst?" },
  { id: 64, category: "liebe",
    majority: "Was würdest du nicht tun, egal wie verliebt du bist?",
    liar: "Was hast du gemacht, das du vorher fest ausgeschlossen hattest?" },
  { id: 65, category: "liebe",
    majority: "Wie merkst du, dass du jemanden magst?",
    liar: "Woran merkst du, dass eine Verbindung keine Zukunft hat?" },

  // ── KINDHEIT ──────────────────────────────────────────────────────────────
  { id: 66, category: "kindheit",
    majority: "Was war dein Lieblingsspielzeug als Kind?",
    liar: "Was war ein Spielzeug das du hattest, aber eigentlich nie wolltest?" },
  { id: 67, category: "kindheit",
    majority: "Was war deine Lieblingsbeschäftigung nach der Schule?",
    liar: "Was musstest du als Kind tun, das du gehasst hast?" },
  { id: 68, category: "kindheit",
    majority: "Was war dein Lieblingsessen als Kind?",
    liar: "Was wurde dir als Kind als lecker verkauft, das du nie mochtest?" },
  { id: 69, category: "kindheit",
    majority: "Welcher Cartoon oder welche Kindersendung war dein absolutes Must-Watch?",
    liar: "Welche Kindersendung fandst du heimlich langweilig, obwohl alle sie liebten?" },
  { id: 70, category: "kindheit",
    majority: "Was wolltest du als Kind unbedingt werden?",
    liar: "Was haben Erwachsene dir als Beruf empfohlen, das du dir nie vorstellen konntest?" },
  { id: 71, category: "kindheit",
    majority: "Welches Kindheitserlebnis machst du immer wieder zum Thema bei Familienfeiern?",
    liar: "Welches Kindheitserlebnis lässt du aus, weil es dir noch heute peinlich ist?" },
  { id: 72, category: "kindheit",
    majority: "Was war deine absolut coolste Erinnerung aus der Grundschule?",
    liar: "Was war ein Schulerlebnis, das du am liebsten aus dem Gedächtnis löschen würdest?" },
,

  // ── Getränke ──
// ── GETRÄNKE (neue Kategorie) ──────────────────────────────────────────
  { id: 101, category: "getraenke",
    majority: "Welches alkoholische Getränk ist deiner Meinung nach völlig underrated?",
    liar: "Welches alkoholische Getränk findest du hoffnungslos overrated, auch wenn alle es feiern?" },
  { id: 102, category: "getraenke",
    majority: "Was ist dein Go-to-Getränk wenn du feiern gehst?",
    liar: "Was bestellst du nur, damit es nach Partylaune aussieht, aber eigentlich hasst du es?" },
  { id: 103, category: "getraenke",
    majority: "Welches Bier würdest du jedem empfehlen, der kein Bier mag?",
    liar: "Welches Bier trinken alle auf Partys, das du aber wirklich nicht ausstehen kannst?" },
  { id: 104, category: "getraenke",
    majority: "Welcher Cocktail ist dein absoluter Liebling?",
    liar: "Welchen überteuerten Cocktail bestellst du einmal und bereust es sofort?" },
  { id: 105, category: "getraenke",
    majority: "Was ist das beste alkoholfreie Getränk auf einer Party?",
    liar: "Was trinkst du nur um nüchtern zu wirken, findest es aber furchtbar?" },
  { id: 106, category: "getraenke",
    majority: "Welcher Shot ist bei euch Pflicht wenn alle zusammen feiern?",
    liar: "Welcher Shot macht dich schon beim Geruch würgen?" },
  { id: 107, category: "getraenke",
    majority: "Welches Getränk verbindest du mit dem besten Abend deines Lebens?",
    liar: "Welches Getränk hat dir mal den schlimmsten Kater beschert?" },
  { id: 108, category: "getraenke",
    majority: "Wein oder Bier – und warum?",
    liar: "Weder Wein noch Bier – was trinkst du wirklich lieber als beides?" },
  { id: 109, category: "getraenke",
    majority: "Welches Getränk würdest du für immer aus deinem Leben streichen können?",
    liar: "Was hast du mal geschworen nie wieder zu trinken – und dann doch wieder getrunken?" },
  { id: 110, category: "getraenke",
    majority: "Was ist dein Morgen-nach-Kater-Getränk?",
    liar: "Was empfehlen alle gegen Kater, das bei dir überhaupt nicht wirkt?" },
  { id: 111, category: "getraenke",
    majority: "Welches Länder-Getränk hat dich auf Reisen überrascht?",
    liar: "Welches 'traditionelle' Getränk wolltest du unbedingt probieren und warst dann enttäuscht?" },
  { id: 112, category: "getraenke",
    majority: "Was ist ein Getränk, das du als Kind probiert und geliebt hast?",
    liar: "Was hast du als Kind getrunken, das du heute nicht mehr anrühren würdest?" },

  // ── PARTY & AUSGEHEN ──────────────────────────────────────────────────
  { id: 113, category: "party",
    majority: "Was ist das absolute Must-Have-Lied auf jeder Party?",
    liar: "Welcher Song kommt auf jeder Party und macht die Stimmung für dich sofort kaputt?" },
  { id: 114, category: "party",
    majority: "Was ist dein Ritual bevor du auf eine Party gehst?",
    liar: "Was machst du auf Partys, das niemand wissen sollte?" },
  { id: 115, category: "party",
    majority: "Welche Party-Situation rettet immer die Stimmung?",
    liar: "Was tötet auf einer Party die Atmosphäre sofort?" },
  { id: 116, category: "party",
    majority: "Was ist der beste Moment auf einer gelungenen Hausparty?",
    liar: "Was passiert auf Hauspartys immer, das du heimlich nervt?" },
  { id: 117, category: "party",
    majority: "Was ist das beste Trinkspiel für eine größere Gruppe?",
    liar: "Welches Trinkspiel findest du überschätzt, obwohl alle es spielen wollen?" },
  { id: 118, category: "party",
    majority: "Wann ist für dich der perfekte Zeitpunkt, eine Party zu verlassen?",
    liar: "Wann bleibst du auf einer Party viel länger als du wolltest und warum?" },
  { id: 119, category: "party",
    majority: "Was ist das erste was du auf einer Party machst wenn du ankommst?",
    liar: "Was machst du auf Partys immer zuletzt, obwohl du es als erstes tun solltest?" },
  { id: 120, category: "party",
    majority: "Welcher Party-Typ bist du – Organisator, Animateur oder stiller Genießer?",
    liar: "Welcher Party-Typ nervt dich am meisten – und bist du manchmal selbst einer davon?" },

  // ── ESSEN (erweitert) ──────────────────────────────────────────────────
  { id: 121, category: "essen",
    majority: "Was ist das beste Essen nach einem langen Partyabend?",
    liar: "Was bestellst du betrunken immer und bereust es nüchtern?" },
  { id: 122, category: "essen",
    majority: "Welches Fast-Food-Gericht ist absolut unschlagbar?",
    liar: "Welches Fast-Food-Gericht hat dich nach dem Hype enttäuscht?" },
  { id: 123, category: "essen",
    majority: "Was kochst du, wenn du nur die Reste aus dem Kühlschrank nimmst?",
    liar: "Was hast du mal aus Resten zusammengestellt und es war absolut ungenießbar?" },
  { id: 124, category: "essen",
    majority: "Welches Essen aus einem anderen Land könntest du täglich essen?",
    liar: "Welches internationale Gericht wolltest du probieren und würdest es nicht wiederholen?" },
  { id: 125, category: "essen",
    majority: "Was ist das überbewertetste Food-Trend-Gericht der letzten Jahre?",
    liar: "Was haben alle als Food-Trend abgestempelt, das du heimlich aber wirklich magst?" },
  { id: 126, category: "essen",
    majority: "Was ist dein Geheimrezept oder deine geheime Zutat bei einem Gericht?",
    liar: "Was gibst du als selbst gekocht aus, das du eigentlich immer kaufst?" },
  { id: 127, category: "essen",
    majority: "Süß oder salzig – wenn du nur eine Kategorie fürs Leben wählen müsstest?",
    liar: "Was ist eine Kombination aus süß und salzig, die alle eklig finden, du aber liebst?" },
  { id: 128, category: "essen",
    majority: "Welches Essen hast du als Kind gehasst und magst es jetzt?",
    liar: "Was mochtest du als Kind und kannst als Erwachsener nicht mehr verstehen warum?" },
  { id: 129, category: "essen",
    majority: "Was ist für dich das perfekte Picknick-Essen?",
    liar: "Was bringt immer jemand zum Picknick mit, das du nicht essen willst aber höflich nimmst?" },
  { id: 130, category: "essen",
    majority: "Welches Restaurant in deiner Stadt empfiehlst du jedem?",
    liar: "Welches Restaurant läuft gut, das du aber nach einem Besuch nie wiedergehen würdest?" },

  // ── SOZIALES & PERSÖNLICHKEIT ─────────────────────────────────────────
  { id: 131, category: "soziales",
    majority: "Was ist das Peinlichste, das du mal in einer Gruppe gemacht hast?",
    liar: "Was war das Peinlichste, das jemand anderes gemacht hat – und du hast es ausgelöst?" },
  { id: 132, category: "soziales",
    majority: "Was sagst du, wenn du eine Einladung ablehnen willst aber nicht die Wahrheit sagen kannst?",
    liar: "Was war deine unkreativste Ausrede und es hat trotzdem funktioniert?" },
  { id: 133, category: "soziales",
    majority: "Was ist deine größte Stärke in einer Gruppe?",
    liar: "Was glauben andere ist deine Stärke, die in Wirklichkeit eher eine Schwäche ist?" },
  { id: 134, category: "soziales",
    majority: "Wie reagierst du, wenn jemand einen Witz auf deine Kosten macht?",
    liar: "Wann hast du einen Witz auf jemand anderen gemacht und es sofort bereut?" },
  { id: 135, category: "soziales",
    majority: "Was ist eine Eigenschaft, die du bei anderen bewunderst aber selbst nicht hast?",
    liar: "Was glaubst du an dir selbst als Stärke, die andere eher als nervig empfinden?" },
  { id: 136, category: "soziales",
    majority: "Wie verhältst du dich, wenn du jemanden nicht magst, aber höflich sein musst?",
    liar: "Wann warst du so unangenehm zu jemandem, dass du es heute noch bereust?" },
  { id: 137, category: "soziales",
    majority: "Was ist eine soziale Situation, die dir leicht fällt, anderen aber schwer?",
    liar: "Was fällt dir in sozialen Situationen heimlich schwer, obwohl du es nach außen leicht wirken lässt?" },
  { id: 138, category: "soziales",
    majority: "Was machst du, wenn du auf einer Party niemanden kennst?",
    liar: "Was machst du auf Partys, wenn du eigentlich lieber woanders wärst?" },

  // ── TECHNOLOGIE & SOCIAL MEDIA ────────────────────────────────────────
  { id: 139, category: "tech",
    majority: "Welche App nutzt du heimlich viel mehr als du zugibst?",
    liar: "Welche App solltest du öfter nutzen, öffnest sie aber so gut wie nie?" },
  { id: 140, category: "tech",
    majority: "Was postest du auf Social Media nie, obwohl du es würdest wenn niemand zusehen würde?",
    liar: "Was hast du gepostet und sofort bereut?" },
  { id: 141, category: "tech",
    majority: "Welche Benachrichtigung auf deinem Handy lässt du am längsten unbeantwortet?",
    liar: "Welche Nachricht hast du gelesen, als ungelesen markiert und nie beantwortet?" },
  { id: 142, category: "tech",
    majority: "Was ist dein größter Smartphone-Guilty-Pleasure?",
    liar: "Was machst du am Handy, das du vor deinen Eltern oder deinem Partner versteckst?" },
  { id: 143, category: "tech",
    majority: "Welches Social-Media-Netzwerk ist für dich noch relevant?",
    liar: "Welches Netzwerk hast du 'aufgehört zu nutzen' und schaust trotzdem täglich rein?" },
  { id: 144, category: "tech",
    majority: "Was ist eine Technologie die du als überbewertet bezeichnest?",
    liar: "Was ist eine Technologie die du abgelehnt hast, aber heimlich gut findest?" },

  // ── SPORT & FITNESS ───────────────────────────────────────────────────
  { id: 145, category: "sport",
    majority: "Welche Sportart würdest du jederzeit ausprobieren wollen?",
    liar: "Welche Sportart hast du mal ausprobiert und nie wieder gemacht?" },
  { id: 146, category: "sport",
    majority: "Was ist dein ehrlichstes Sport-Ziel für dieses Jahr?",
    liar: "Was hast du dir als Fitnessziel vorgenommen und aufgegeben, bevor der Monat rum war?" },
  { id: 147, category: "sport",
    majority: "Welcher Sportler oder welche Sportlerin inspiriert dich?",
    liar: "Welcher gefeierte Sportler ist für dich eigentlich überschätzt?" },
  { id: 148, category: "sport",
    majority: "Was ist deine Lieblingsausrede, um nicht Sport zu machen?",
    liar: "Was war die dümmste Ausrede, die du tatsächlich für Sport genutzt hast?" },
  { id: 149, category: "sport",
    majority: "Was ist deiner Meinung nach keine richtige Sportart – egal was andere sagen?",
    liar: "Welche 'richtige' Sportart macht dir heimlich gar keinen Spaß?" },

  // ── FILME (erweitert) ──────────────────────────────────────────────────
  { id: 150, category: "filme",
    majority: "Welche Streaming-Plattform ist deiner Meinung nach ihr Geld wert?",
    liar: "Welche Plattform bezahlst du und nutzt sie kaum?" },
  { id: 151, category: "filme",
    majority: "Welcher Film-Reboot oder welches Sequel war besser als das Original?",
    liar: "Welches gefeierte Sequel war für dich eine Enttäuschung?" },
  { id: 152, category: "filme",
    majority: "Welchen Film hast du erst als Erwachsener gesehen und bereust, ihn nicht früher gesehen zu haben?",
    liar: "Welchen Klassiker hast du jetzt erst gesehen und verstehst den Hype nicht?" },
  { id: 153, category: "filme",
    majority: "Was ist eine Filmgenre das du heimlich liebst, obwohl du es nach außen schlecht redest?",
    liar: "Was ist ein Genre, das du als gut verkauft aber eigentlich nicht magst?" },
  { id: 154, category: "filme",
    majority: "Welcher Filmheld ist für dich eigentlich kein Held?",
    liar: "Welcher Filmschurke hat in Wirklichkeit recht?" },
  { id: 155, category: "filme",
    majority: "Welche Serie hätte nach Staffel 1 aufhören sollen?",
    liar: "Welche Serie schaust du noch obwohl du schon lange aufgehört hast sie zu mögen?" },

  // ── MUSIK (erweitert) ─────────────────────────────────────────────────
  { id: 156, category: "musik",
    majority: "Welches Lied kennst du auswendig, ohne es je absichtlich gelernt zu haben?",
    liar: "Welches Lied tust du so als würdest du es kennen, aber die Hälfte singst du nur Lalala?" },
  { id: 157, category: "musik",
    majority: "Welcher Künstler produziert konstant gute Musik seit Jahren?",
    liar: "Welcher einst gute Künstler hat sich zu sehr verändert und enttäuscht dich?" },
  { id: 158, category: "musik",
    majority: "Was ist ein Song, der dich in eine bestimmte Erinnerung zurückversetzt?",
    liar: "Was ist ein Song, den alle mit schönen Momenten verbinden, der dich aber an etwas Unangenehmes erinnert?" },
  { id: 159, category: "musik",
    majority: "Welches Musikinstrument hättest du gerne gelernt?",
    liar: "Welches Instrument hast du angefangen zu lernen und nach kurzer Zeit aufgehört?" },
  { id: 160, category: "musik",
    majority: "Was ist der überbewertetste Song der letzten Jahre?",
    liar: "Was ist ein Song den alle schlecht reden, den du aber heimlich magst?" },

  // ── FUSSBALL (erweitert) ──────────────────────────────────────────────
  { id: 161, category: "fussball",
    majority: "Welchen Verein wärst du gerne Fan, wenn du keinen hättest?",
    liar: "Welchen Verein verfolgst du heimlich, obwohl du sagst du interessierst dich nicht?" },
  { id: 162, category: "fussball",
    majority: "Welcher Fußballer hätte zu einem anderen Verein gepasst als er gespielt hat?",
    liar: "Welcher gefeierte Wechsel war für dich offensichtlich eine Katastrophe?" },
  { id: 163, category: "fussball",
    majority: "Was war der schlimmste Kommentar den du in einem Fußballspiel gehört hast?",
    liar: "Was hast du mal im Affekt gerufen das du dir danach gewünscht hast nicht gesagt zu haben?" },
  { id: 164, category: "fussball",
    majority: "Welche Nationalmannschaft spielt den schönsten Fußball?",
    liar: "Welche Nationalmannschaft wird überschätzt obwohl sie nie liefert wenn es darauf ankommt?" },
  { id: 165, category: "fussball",
    majority: "Welches Fußball-Regelwerk würdest du sofort ändern?",
    liar: "Welche Regel im Fußball findest du eigentlich gut, traust dich aber nicht zu sagen?" },

  // ── ALLTAG (erweitert) ────────────────────────────────────────────────
  { id: 166, category: "alltag",
    majority: "Was ist ein Lebenshack den du wirklich täglich nutzt?",
    liar: "Was empfiehlst du anderen als Lebenshack, tust es selbst aber nie?" },
  { id: 167, category: "alltag",
    majority: "Was ist das erste was du morgens kaufst wenn du ausgeschlafen bist?",
    liar: "Was kaufst du immer mit dem Vorsatz 'heute esse/trinke ich gesund' und isst es dann doch nicht?" },
  { id: 168, category: "alltag",
    majority: "Welche Aufgabe zuhause machst du immer sofort?",
    liar: "Was stapelt sich bei dir zuhause bis es wirklich nicht mehr geht?" },
  { id: 169, category: "alltag",
    majority: "Was ist dein Lieblingsweg um einen schlechten Tag abzuschütteln?",
    liar: "Was machst du nach einem schlechten Tag, das eigentlich nicht hilft aber du es trotzdem tust?" },
  { id: 170, category: "alltag",
    majority: "Was ist eine Angewohnheit von dir, die andere nervig finden könnten?",
    liar: "Was nervt dich an anderen, machst du aber selbst genauso?" },
  { id: 171, category: "alltag",
    majority: "Was hast du dir vorgenommen diese Woche zu erledigen – und wird es klappen?",
    liar: "Was steht schon seit Wochen auf deiner To-do-Liste und du weißt, es kommt nie dran?" },
  { id: 172, category: "alltag",
    majority: "Was ist dein ehrliches Verhältnis zu Sport und Bewegung?",
    liar: "Was machst du und sagst es sei Sport, obwohl jeder weiß das es keiner ist?" },

  // ── REISEN (erweitert) ────────────────────────────────────────────────
  { id: 173, category: "urlaub",
    majority: "Was ist ein Urlaubsziel das du immer wieder besuchst?",
    liar: "Wohin bist du mehrfach gefahren obwohl es jedes Mal schlechter war als davor?" },
  { id: 174, category: "urlaub",
    majority: "Was ist das Seltsamste das du jemals im Urlaub gegessen hast?",
    liar: "Was hast du im Urlaub probiert und konnte es nicht herunterschlucken?" },
  { id: 175, category: "urlaub",
    majority: "Strand oder Berge – und was magst du daran wirklich?",
    liar: "Was wählst du nur weil es der Rest der Gruppe will, obwohl du lieber woanders wärst?" },
  { id: 176, category: "urlaub",
    majority: "Was ist das Beste an Backpacking oder Budget-Reisen?",
    liar: "Was hast du beim Reisen als Erlebnis verkauft, war aber eigentlich einfach zu billig?" },
  { id: 177, category: "urlaub",
    majority: "Was ist dein ehrlichster Reisetyp – Aktivurlaub, Relaxen oder Kultur?",
    liar: "Was buchst du als Urlaub und verbringst die meiste Zeit dennoch im Hotel?" },

  // ── BEZIEHUNGEN & DATING (erweitert) ──────────────────────────────────
  { id: 178, category: "liebe",
    majority: "Was ist ein Dating-Red-Flag, den du wirklich ernst nimmst?",
    liar: "Was ist ein Red-Flag, den du mal ignoriert hast – und bereust du es?" },
  { id: 179, category: "liebe",
    majority: "Was ist deine ehrlichste Meinung zu Dating-Apps?",
    liar: "Was sagst du über Dating-Apps, tust aber heimlich das Gegenteil?" },
  { id: 180, category: "liebe",
    majority: "Was ist das Komischste was dir je auf einem Date passiert ist?",
    liar: "Was war das Komischste, das du auf einem Date selbst verursacht hast?" },
  { id: 181, category: "liebe",
    majority: "Was ist eine Liebes-Geste, die du wirklich bedeutsam findest?",
    liar: "Was wird als romantisch verkauft, findest du aber eigentlich peinlich?" },
  { id: 182, category: "liebe",
    majority: "Was ist die ehrlichste Eigenschaft, die du dir in einem Partner wünschst?",
    liar: "Was sagst du dass du in einem Partner willst, das sich aber nie in deinen echten Entscheidungen widerspiegelt?" },

  // ── GELD & KONSUM ─────────────────────────────────────────────────────
  { id: 183, category: "geld",
    majority: "Wofür gibst du Geld aus und bereust es nie?",
    liar: "Wofür hast du mal viel Geld ausgegeben und findest es im Nachhinein komplett unnötig?" },
  { id: 184, category: "geld",
    majority: "Was ist ein Luxus, den du dir regelmäßig gönnst?",
    liar: "Was gönnst du dir heimlich regelmäßig, das du vor anderen nicht zugeben würdest?" },
  { id: 185, category: "geld",
    majority: "Wo sparst du wirklich Geld ein ohne dass du es merkst?",
    liar: "Wo sagst du du sparst Geld, gibst aber eigentlich genauso viel aus?" },
  { id: 186, category: "geld",
    majority: "Was war dein bisher bester Kauf?",
    liar: "Was war dein bisher sinnlosester Kauf, den du trotzdem nicht bereust?" },
  { id: 187, category: "geld",
    majority: "Was ist etwas, für das du bereit bist mehr zu zahlen als andere?",
    liar: "Was gibst du als Qualitätsmerkmal aus, kaufst aber trotzdem immer die billigste Version?" },

  // ── SCHULE & BILDUNG ──────────────────────────────────────────────────
  { id: 188, category: "schule",
    majority: "Welches Schulfach hat dich wirklich interessiert?",
    liar: "In welchem Fach hast du so getan als würdest du mitarbeiten, aber kein Wort davon verstanden?" },
  { id: 189, category: "schule",
    majority: "Was war dein ehrlichstes Lernmuster vor Prüfungen?",
    liar: "Wann hast du eine Prüfung bestanden obwohl du gar nicht oder kaum gelernt hattest?" },
  { id: 190, category: "schule",
    majority: "Welcher Lehrer oder welche Lehrerin hat dich wirklich geprägt?",
    liar: "Welcher Lehrer galt als super – den du aber heimlich nicht mochtest?" },
  { id: 191, category: "schule",
    majority: "Was hast du in der Schule gelernt, das du heute noch täglich nutzt?",
    liar: "Was haben sie in der Schule als wichtig verkauft, das du seitdem nie wieder gebraucht hast?" },

  // ── NATUR & TIERE ─────────────────────────────────────────────────────
  { id: 192, category: "natur",
    majority: "Welches Tier fasziniert dich am meisten?",
    liar: "Welches Tier findest du eigentlich gruselig, obwohl alle sagen es ist niedlich?" },
  { id: 193, category: "natur",
    majority: "Hund oder Katze – und was sagt das über dich aus?",
    liar: "Welches Haustier hättest du heimlich gern, das niemand für dich erwartet?" },
  { id: 194, category: "natur",
    majority: "Was ist deine Lieblingszeit im Jahr und warum?",
    liar: "Welche Jahreszeit beschwerst du dich am meisten drüber, obwohl du sie eigentlich nicht schlimm findest?" },
  { id: 195, category: "natur",
    majority: "Wie nachhaltig lebst du wirklich – eine ehrliche Einschätzung?",
    liar: "Was propagierst du als nachhaltig, machst es aber selbst so gut wie nie?" },

  // ── WILDE KARTEN (kreative Fragen) ───────────────────────────────────
  { id: 196, category: "wildcard",
    majority: "Welche Superkraft hättest du gerne – ehrlich und nicht das was alle sagen?",
    liar: "Welche Superkraft klingt cool, würdest du aber im Alltag sofort bereuen?" },
  { id: 197, category: "wildcard",
    majority: "In welchem Film-Genre würde dein Leben am besten funktionieren?",
    liar: "In welchem Film-Genre wärst du der Erste, der stirbt oder als Antagonist endet?" },
  { id: 198, category: "wildcard",
    majority: "Wenn du eine Person einladen könntest für ein Abendessen – wen und warum?",
    liar: "Welche berühmte Person klingt interessant aber würdest nach 10 Minuten bereuen eingeladen zu haben?" },
  { id: 199, category: "wildcard",
    majority: "Was wäre dein Geständnis, wenn du 24 Stunden komplett ehrlich sein müsstest?",
    liar: "Was würdest du als erste Lüge erzählen, wenn du nach 24 Stunden Ehrlichkeit wieder lügen dürftest?" },
  { id: 200, category: "wildcard",
    majority: "Was ist die seltsamste Theorie die du hast und niemandem erzählst?",
    liar: "Was haben andere als Theorie erzählt, das du öffentlich abgelehnt aber heimlich für plausibel gehalten hast?" },
  { id: 201, category: "wildcard",
    majority: "Welche komplett unnötige Fähigkeit hast du entwickelt?",
    liar: "Was hast du wochenlang geübt, das am Ende komplett nutzlos war?" },
  { id: 202, category: "wildcard",
    majority: "Was wäre deine absolute Dealbreaker-Frage beim Speed-Dating?",
    liar: "Was hast du als Dealbreaker bezeichnet, aber dann doch ignoriert?" },
  { id: 203, category: "wildcard",
    majority: "Welche App auf deinem Handy erklärt am besten wer du wirklich bist?",
    liar: "Welche App auf deinem Handy würde dich am peinlichsten dastehen lassen, wenn alle sie sehen?" },
  { id: 204, category: "wildcard",
    majority: "Was ist dein ehrlichstes Hobby, das du in Bewerbungen nicht angibst?",
    liar: "Was gibst du als Hobby in Bewerbungen an, das du eigentlich kaum machst?" },
  { id: 205, category: "wildcard",
    majority: "Welches Sprichwort trifft auf dich am ehesten zu?",
    liar: "Welches Sprichwort zitierst du oft, das auf dich selbst überhaupt nicht zutrifft?" },
];


export const LUEGNERJAGD_CATEGORY_LABELS: Record<LuegnerjagdCategory, string> = {
  filme: "Filme & Serien",
  musik: "Musik",
  fussball: "Fußball",
  alltag: "Alltag",
  essen: "Essen & Trinken",
  urlaub: "Urlaub & Reisen",
  freundschaft: "Freundschaft",
  arbeit: "Arbeit & Studium",
  liebe: "Liebe & Dating",
  kindheit: "Kindheit",
  getraenke: "Getränke",
  party: "Party & Ausgehen",
  soziales: "Soziales",
  tech: "Tech & Social Media",
  sport: "Sport & Fitness",
  geld: "Geld & Konsum",
  schule: "Schule & Bildung",
  natur: "Natur & Tiere",
  wildcard: "Wilde Karte",
};

export const LUEGNERJAGD_CATEGORY_EMOJI: Record<LuegnerjagdCategory, string> = {
  filme: "🎬",
  musik: "🎵",
  fussball: "⚽",
  alltag: "☕",
  essen: "🍕",
  urlaub: "✈️",
  freundschaft: "🤝",
  arbeit: "💼",
  liebe: "💘",
  kindheit: "🧸",
  getraenke: "🍺",
  party: "🎉",
  soziales: "👥",
  tech: "📱",
  sport: "🏃",
  geld: "💸",
  schule: "📚",
  natur: "🌿",
  wildcard: "🃏",
};
