// 99 Fragen – "Wer würde am ehesten…" Trinkspiel.
// Vorleser liest leise → gibt Handy an die Person weiter, auf die es am ehesten zutrifft → diese liest laut vor & trinkt.

export type Fragen99Category = "classic" | "action" | "spicy" | "deep";

export interface Fragen99Question {
  text: string;
  category: Fragen99Category;
}

export const FRAGEN99_CATEGORY_LABEL: Record<Fragen99Category, string> = {
  classic: "Klassisch",
  action: "Party",
  spicy: "Spicy",
  deep: "Tief",
};

export const FRAGEN99_CATEGORY_EMOJI: Record<Fragen99Category, string> = {
  classic: "🍻",
  action: "🎉",
  spicy: "🌶️",
  deep: "💭",
};

export const FRAGEN99: Fragen99Question[] = [
  // ===== Klassisch =====
  { text: "Wer würde am ehesten verschlafen und zu spät zur eigenen Hochzeit kommen?", category: "classic" },
  { text: "Wer würde am ehesten den Schlüssel im Auto vergessen – mit laufendem Motor?", category: "classic" },
  { text: "Wer würde am ehesten beim Wandern verloren gehen?", category: "classic" },
  { text: "Wer würde am ehesten ein teures Geschenk gegen ein billigeres umtauschen?", category: "classic" },
  { text: "Wer würde am ehesten in der Schlange an der Kasse mit dem Kassierer streiten?", category: "classic" },
  { text: "Wer würde am ehesten heimlich Tagebuch führen?", category: "classic" },
  { text: "Wer würde am ehesten in einem Quiz die einfachste Frage falsch beantworten?", category: "classic" },
  { text: "Wer würde am ehesten 3 Stunden im Bad verbringen, bevor er rausgeht?", category: "classic" },
  { text: "Wer würde am ehesten am Selbstbedienungs-Kassenautomaten verzweifeln?", category: "classic" },
  { text: "Wer würde am ehesten unter Tränen einen Pixar-Film schauen?", category: "classic" },
  { text: "Wer würde am ehesten beim Karaoke das Mikro nicht mehr hergeben?", category: "classic" },
  { text: "Wer würde am ehesten in einem fremden Land aus Versehen die falsche Toilette betreten?", category: "classic" },
  { text: "Wer würde am ehesten den ganzen Sonntag im Bett bleiben?", category: "classic" },
  { text: "Wer würde am ehesten beim ersten Date die Rechnung teilen wollen?", category: "classic" },
  { text: "Wer würde am ehesten die Spülmaschine falsch einräumen – und es nicht zugeben?", category: "classic" },
  { text: "Wer würde am ehesten beim Möbelaufbauen die Anleitung wegwerfen?", category: "classic" },
  { text: "Wer würde am ehesten eine TV-Show schauen und die ganze Zeit kommentieren?", category: "classic" },
  { text: "Wer würde am ehesten beim Friseur sagen 'Mach was du willst'?", category: "classic" },
  { text: "Wer würde am ehesten in einer Diskussion einfach Recht behalten wollen?", category: "classic" },
  { text: "Wer würde am ehesten den ganzen Kühlschrank leer essen, nachts um 3?", category: "classic" },
  { text: "Wer würde am ehesten ein Kettenmail-Versprechen ernst nehmen?", category: "classic" },
  { text: "Wer würde am ehesten beim Putzen sein Lieblingslied tanzend mitsingen?", category: "classic" },
  { text: "Wer würde am ehesten Influencer werden – nur halt heimlich?", category: "classic" },
  { text: "Wer würde am ehesten den Pizzaboten als beste Freundin/besten Freund bezeichnen?", category: "classic" },
  { text: "Wer würde am ehesten beim Sport nach 5 Minuten aufgeben?", category: "classic" },

  // ===== Party =====
  { text: "Wer würde am ehesten als Erstes auf den Tisch tanzen?", category: "action" },
  { text: "Wer würde am ehesten auf einer Party einschlafen?", category: "action" },
  { text: "Wer würde am ehesten den DJ um ein Lied bitten, das niemand kennt?", category: "action" },
  { text: "Wer würde am ehesten betrunken seinen Ex anrufen?", category: "action" },
  { text: "Wer würde am ehesten am nächsten Tag nichts mehr von der Nacht wissen?", category: "action" },
  { text: "Wer würde am ehesten die Bar bis zum Schluss leer trinken?", category: "action" },
  { text: "Wer würde am ehesten in der Disco fremde Leute umarmen?", category: "action" },
  { text: "Wer würde am ehesten betrunken ein Tattoo stechen lassen?", category: "action" },
  { text: "Wer würde am ehesten eine Pfütze ignorieren und einfach durchlaufen?", category: "classic" },
  { text: "Wer würde am ehesten in jedem Club die VIP-Lounge stürmen?", category: "action" },
  { text: "Wer würde am ehesten beim Beer Pong unfair sein?", category: "action" },
  { text: "Wer würde am ehesten morgens noch das Bier von gestern austrinken?", category: "action" },
  { text: "Wer würde am ehesten Shots ausgeben, ohne zu fragen?", category: "action" },
  { text: "Wer würde am ehesten als Erstes 'noch ein letztes Bier' rufen – um 4 Uhr morgens?", category: "action" },
  { text: "Wer würde am ehesten betrunken Pizza bestellen und noch beim Tippen einschlafen?", category: "action" },
  { text: "Wer würde am ehesten die Hausparty-Playlist gegen den Willen aller wechseln?", category: "action" },
  { text: "Wer würde am ehesten als Erstes auf den Dancefloor stürmen?", category: "action" },
  { text: "Wer würde am ehesten den Türsteher um eine Umarmung bitten?", category: "action" },
  { text: "Wer würde am ehesten am Tresen stehen und alle fünf Minuten neue Shots bestellen?", category: "action" },
  { text: "Wer würde am ehesten ungefragt das Mikro in der Karaoke-Bar übernehmen?", category: "action" },
  { text: "Wer würde am ehesten betrunken einen Strafzettel bekommen, weil er auf einer Bank schläft?", category: "action" },
  { text: "Wer würde am ehesten eine Sektflasche auf Ex trinken?", category: "action" },
  { text: "Wer würde am ehesten auf einer Hochzeit zu betrunken für die Rede werden?", category: "action" },
  { text: "Wer würde am ehesten mitten auf der Tanzfläche einen Kreis aufmachen und alle dazu einladen?", category: "action" },
  { text: "Wer würde am ehesten nach 2 Bier behaupten, er sei der beste Tänzer des Abends?", category: "action" },

  // ===== Spicy =====
  { text: "Wer würde am ehesten One-Night-Stands über Beziehungen stellen?", category: "spicy" },
  { text: "Wer würde am ehesten ein peinliches Sex-Geheimnis haben?", category: "spicy" },
  { text: "Wer würde am ehesten beim Sex aus Versehen den falschen Namen sagen?", category: "spicy" },
  { text: "Wer würde am ehesten Nacktfotos verschicken – an die falsche Person?", category: "spicy" },
  { text: "Wer würde am ehesten in der Sauna nackt einfach Hi sagen?", category: "spicy" },
  { text: "Wer würde am ehesten beim ersten Date schon Sex haben?", category: "spicy" },
  { text: "Wer würde am ehesten mit der besten Freundin / dem besten Freund des Partners flirten?", category: "spicy" },
  { text: "Wer würde am ehesten in einem Strip-Club als Erste auf die Bühne wollen?", category: "spicy" },
  { text: "Wer würde am ehesten heimlich Pornos bei der Arbeit schauen?", category: "spicy" },
  { text: "Wer würde am ehesten in einer Hotelbar fremdgehen?", category: "spicy" },
  { text: "Wer würde am ehesten mehrere Affären gleichzeitig haben?", category: "spicy" },
  { text: "Wer würde am ehesten beim Sex laut lachen?", category: "spicy" },
  { text: "Wer würde am ehesten ein Sex-Spielzeug öffentlich kaufen, ohne zu erröten?", category: "spicy" },
  { text: "Wer würde am ehesten ein Dating-Profil mit komplett falschen Fotos haben?", category: "classic" },
  { text: "Wer würde am ehesten auf der Hochzeit eines Ex erscheinen – ungeladen?", category: "spicy" },
  { text: "Wer würde am ehesten auf einem Campingplatz für alle hörbar streiten?", category: "action" },
  { text: "Wer würde am ehesten heimlich noch Kontakt zum Ex haben?", category: "spicy" },
  { text: "Wer würde am ehesten beim Date zu früh sagen 'Ich liebe dich'?", category: "spicy" },
  { text: "Wer würde am ehesten am ersten Morgen heimlich verschwinden?", category: "spicy" },
  { text: "Wer würde am ehesten in einer offenen Beziehung leben?", category: "spicy" },
  { text: "Wer würde am ehesten den Crush des besten Freundes / der besten Freundin daten?", category: "spicy" },
  { text: "Wer würde am ehesten beim Sex zu laut sein und die Nachbarn wecken?", category: "spicy" },
  { text: "Wer würde am ehesten ein Sextape drehen?", category: "spicy" },
  { text: "Wer würde am ehesten Insta-Stalking auf Profi-Niveau betreiben?", category: "classic" },
  { text: "Wer würde am ehesten Schluss machen per WhatsApp-Sprachnachricht?", category: "classic" },

  // ===== Tief =====
  { text: "Wer würde am ehesten einem Freund das Herz brechen, ohne es zu merken?", category: "deep" },
  { text: "Wer würde am ehesten heimlich verliebt sein – ohne es jemals zu sagen?", category: "deep" },
  { text: "Wer würde am ehesten in Therapie gehen und nichts davon erzählen?", category: "deep" },
  { text: "Wer würde am ehesten ein Doppelleben führen?", category: "deep" },
  { text: "Wer würde am ehesten alles aufgeben für die wahre Liebe?", category: "deep" },
  { text: "Wer würde am ehesten ein Geheimnis bis ins Grab tragen?", category: "deep" },
  { text: "Wer würde am ehesten der treueste Freund im Raum sein?", category: "deep" },
  { text: "Wer würde am ehesten alles für die Familie aufgeben?", category: "deep" },
  { text: "Wer würde am ehesten in Gedanken meilenweit weg sein, wenn jemand redet?", category: "deep" },
  { text: "Wer würde am ehesten einen Brief schreiben, den niemand jemals lesen wird?", category: "deep" },
  { text: "Wer würde am ehesten alles riskieren für einen Traum?", category: "deep" },
  { text: "Wer würde am ehesten heimlich an einer Sache zweifeln, die alle bewundern?", category: "deep" },
  { text: "Wer würde am ehesten lieber alleine sein als mit den falschen Menschen?", category: "deep" },
  { text: "Wer würde am ehesten einen großen Schmerz hinter einem Lachen verstecken?", category: "deep" },
  { text: "Wer würde am ehesten eine Freundschaft beenden, ohne sie zu erklären?", category: "deep" },
  { text: "Wer würde am ehesten in einer Krise einfach alles stehen lassen und gehen?", category: "deep" },
  { text: "Wer würde am ehesten den Mut haben, alles aufzugeben und einen Traumjob im Ausland anzunehmen?", category: "deep" },
  { text: "Wer würde am ehesten am meisten verzeihen können?", category: "deep" },
  { text: "Wer würde am ehesten heimlich an Schicksal glauben?", category: "deep" },
  { text: "Wer würde am ehesten am längsten an einer alten Liebe festhalten?", category: "deep" },
  { text: "Wer würde am ehesten den Mut haben, im Leben nochmal komplett neu zu starten?", category: "deep" },
  { text: "Wer würde am ehesten den größten Einfluss auf das Leben anderer haben?", category: "deep" },
  { text: "Wer würde am ehesten in einer Krisensituation als Erste:r aufstehen und helfen?", category: "deep" },
  { text: "Wer würde am ehesten heimlich am stärksten sein, obwohl er/sie verletzlich wirkt?", category: "deep" },
  { text: "Wer schon mal beim Kochen etwas so schlimm angebrannt hat, dass die Pfanne weg musste: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal einen Film im Kino verpennt hat: 1 Schluck.", category: "classic" },
  { text: "Wer noch nie eine Pflanze am Leben erhalten hat: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal jemanden auf der Straße verwechselt und angesprochen hat: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal vergessen hat, was er gerade sagen wollte – mitten im Satz: 1 Schluck.", category: "classic" },
  { text: "Wer sein Handy schon mal in der Waschmaschine gewaschen hat: 3 Schlücke.", category: "classic" },
  { text: "Wer schon mal einen Regenschirm im Restaurant oder Café vergessen hat: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal eine Zugverbindung verpasst hat, weil er zu lange auf dem Klo war: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal bei einem Quiz mitgemacht und alle Fragen falsch beantwortet hat: 2 Schlücke.", category: "classic" },
  { text: "Wer noch nie ein Buch zu Ende gelesen hat, das er angefangen hat: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal ein Passwort vergessen hat und gesperrt wurde: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal beim Einparken ein anderes Auto touchiert hat: 3 Schlücke.", category: "classic" },
  { text: "Wer schon mal eine IKEA-Möbel falsch zusammengebaut und es erst am Schluss bemerkt hat: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal eine To-do-Liste geschrieben und nie eine Aufgabe erledigt hat: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal jemandem einen Witz erzählt hat, den die Person schon kannte: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal aus Versehen die falsche Person angerufen hat: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal im Supermarkt die falsche Schlange gewählt hat und ewig gewartet hat: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal ein Rezept gefolgt ist und trotzdem ein Desaster produziert hat: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal beim Spaziergang in eine Pfütze getreten ist: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal ein Geschenk ausgepackt und sich dabei nicht freuen können hat: 2 Schlücke (still).", category: "classic" },
  { text: "Wer schon mal aus Versehen Salz statt Zucker benutzt hat: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal seinen Geburtstag verschlafen hat: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal beim Tanzen jemanden gestoßen oder auf den Fuß getreten hat: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal eine Diät angefangen und am gleichen Tag wieder aufgehört hat: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal eine Bewerbung abgeschickt hat, bevor er fertig war: 3 Schlücke.", category: "classic" },
  { text: "Wer schon mal ein Abonnement vergessen hat zu kündigen: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal beim Selfie unabsichtlich jemanden im Hintergrund fotografiert hat: 1 Schluck.", category: "classic" },
  { text: "Wer noch nie im Leben ein Ei selbst gekocht hat: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal sein Auto nicht mehr gefunden hat auf dem Parkplatz: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal jemanden gebeten hat, etwas zu wiederholen, obwohl man es verstanden hatte: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal eine wichtige Mail in den Spam-Ordner verloren hat: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal auf einer öffentlichen Toilette kein Papier mehr gehabt hat: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal eine Netflix-Serie in einem Tag durchgeschaut hat: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal einen Einkaufszettel zuhause vergessen hat: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal etwas im Internet bestellt und sofort bereut hat: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal seinen Geldbeutel verloren und dann wiedergefunden hat: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal ein Ticket für ein Konzert oder Event verpasst hat, weil er es vergessen hat: 3 Schlücke.", category: "classic" },
  { text: "Wer schon mal beim Lachen Getränk aus der Nase verloren hat: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal seinen eigenen Geburtstag auf einem Formular falsch eingetragen hat: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal ein Wort falsch ausgesprochen hat und erst später gemerkt hat: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal beim Backen ein Zutat vergessen hat: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal den Wecker gestellt aber nicht gehört hat: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal aus Versehen jemandem eine Sprachnachricht geschickt hat die nicht für ihn war: 3 Schlücke.", category: "classic" },
  { text: "Wer schon mal seinen Regenschirm aufgemacht hat und er hat sich umgedreht: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal vergessen hat, die Spülmaschine einzuschalten: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal ein wichtiges Meeting verpasst hat: 3 Schlücke.", category: "classic" },
  { text: "Wer schon mal aus Versehen die falsche Haltestelle genommen hat: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal beim Yoga umgekippt ist: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal im Schlaf geredet hat (laut Zeugenaussagen): 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal beim Sport aufgehört hat, weil das Wetter zu schön war: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal eine Flasche Wein alleine geleert hat: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal Milch weggekippt hat, die noch gut war: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal in einer Fremdsprache geantwortet hat, obwohl jemand Deutsch sprach: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal beim Vorlesen ein Wort übersprungen hat und es trotzdem passte: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal seinen Charger vergessen hat und jemanden um einen gebettelt hat: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal Hausaufgaben abgeschrieben hat: 2 Schlücke.", category: "classic" },
  { text: "Wer noch nie einen Brief per Post geschrieben hat: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal in einem Meeting eingeschlafen ist: 3 Schlücke.", category: "classic" },
  { text: "Wer schon mal beim Aufräumen etwas weggeschmissen hat, das er noch gebraucht hätte: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal eine Einladung abgelehnt hat und dann zu Hause nichts gemacht hat: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal im falschen Zimmer aufgewacht ist: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal beim ersten Date den Kellner verwirrt hat: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal Kleidung gekauft hat, die er nie getragen hat: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal versucht hat, eine Tür zu öffnen, die gesperrt war – mehrfach: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal vergessen hat, das Licht auszumachen: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal ein ganzes Päckchen Kekse in einem Sitz gegessen hat: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal beim Vorstellen einen Namen sofort vergessen hat: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal ein Buch ein zweites Mal gelesen hat, weil er das erste vergessen hatte: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal einen Film empfohlen hat, den er selbst nie gesehen hat: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal im Flugzeug weinen musste – wegen eines Films: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal bei einem Sport mitgemacht hat, den er überhaupt nicht kann: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal eine Konservendose nicht geöffnet bekommen hat: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal Urlaub gebucht und dann abgesagt hat: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal in einer Fußgängerzone mit einem anderen zusammengestoßen ist: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal eine App auf dem Handy gehabt hat, die er nie geöffnet hat: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal beim Karaoke einen Song gewählt hat, dessen Text er nicht kannte: 2 Schlücke.", category: "classic" },
  { text: "Wer noch nie eine Pflanze gegossen hat: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal eine Erkältung erfunden hat, um nicht zur Arbeit zu müssen: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal beim Bowling eine Null gewürfelt hat: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal auf einer Party niemanden gekannt hat und trotzdem geblieben ist: 2 Schlücke.", category: "classic" },
  { text: "Wer noch nie in einem Zelt geschlafen hat: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal eine Dusche mit kaltem Wasser erlebt hat – unfreiwillig: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal mit vollem Mund geredet hat: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal jemanden aus Versehen mit dem Nachnamen statt Vornamen angesprochen hat: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal zu früh zu einer Veranstaltung erschienen ist: 1 Schluck.", category: "classic" },
  { text: "Wer noch nie eine Weintraube gegessen hat: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal beim Frühstück Mittag- oder Abendessen gegessen hat: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal eine Katze oder einen Hund geärgert hat und gebissen wurde: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal vergessen hat, wann Sommer- oder Winterzeit war: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal beim Joggen umgeknickt ist: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal aus Versehen seinen Schüssel in der Wohnung eingeschlossen hat: 2 Schlücke.", category: "classic" },
  { text: "Wer noch nie ein Museum besucht hat: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal beim Wandern falsch abgebogen ist: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal beim Sport weiter gemacht hat, obwohl er sich verletzt hat: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal jemandem beim Umzug geholfen hat: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal eine Prüfung oder einen Test ohne Lernen bestanden hat: 2 Schlücke.", category: "classic" },
  { text: "Wer noch nie einen Liebesbrief geschrieben hat: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal aus Versehen das Licht anlassen und nicht schlafen können hat: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal eine Verabredung vergessen hat: 3 Schlücke.", category: "classic" },
  { text: "Wer schon mal beim Tischtennis an einer einfachen Rückgabe gescheitert ist: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal etwas aus dem Ausland mitgebracht hat, das im Koffer kaputt gegangen ist: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal in der Sauna eingeschlafen ist: 2 Schlücke.", category: "classic" },
  { text: "Wer noch nie Sushi gegessen hat: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal beim Zahnarzt weinen musste: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal Salz ins Getränk statt Zucker gegeben hat: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal beim Einschlafen gedacht hat, gefallen zu sein: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal eine Essenslieferung kalt erhalten hat: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal eine Socke verloren hat – dauerhaft: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal beim Klettern Angst bekommen und abgebrochen hat: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal vergessen hat, seinen Geburtstag anzukündigen: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal mehr Geld ausgegeben hat, als er wollte – an einem einzigen Abend: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal auf einer Treppe stolperte und so getan hat, als wäre nichts: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal einen Fernseher ohne Fernbedienung benutzt hat: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal Essen aus dem Mülleimer gerettet hat, weil es noch gut war: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal eine E-Mail an alle gesendet hat, die nur für eine Person gedacht war: 3 Schlücke.", category: "classic" },
  { text: "Wer schon mal bei einem Konzert die Band nicht erkannt hat: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal beim Googeln etwas gefunden hat, das er lieber nicht gewusst hätte: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal einen QR-Code scannen müssen und nicht gewusst hat wie: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal beim Spaziergang mit dem Handy in einen Laternenpfahl gelaufen ist: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal stundenlang nach etwas gesucht hat, das die ganze Zeit in der Hand war: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal beim Bezahlen zu wenig Bargeld hatte: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal beim ersten Versuch ein Selfie gemacht hat, das direkt perfekt war: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal beim Trampolinspringen gefallen ist: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal vergessen hat, was er im Laden kaufen wollte: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal beim Aufstehen sein Knie gestoßen hat: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal einem Kind bei einem Videospiel geholfen hat und trotzdem verloren hat: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal ein Tier auf der Straße angefasst hat, obwohl er es nicht sollte: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal beim ersten Driving-Date in die falsche Richtung gefahren ist: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal eine Überraschungsparty verraten hat: 3 Schlücke.", category: "classic" },
  { text: "Wer schon mal im Dunkeln gegen eine Wand gelaufen ist: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal vergessen hat, den Ofen auszumachen: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal Hausaufgaben in der Schule abgegeben hat, die die Person neben ihm abgeschrieben hatte: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal beim Kuchenbacken vergessen hat, Backpulver zu nehmen: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal bei einer Reise das Ticket falsch gebucht hat: 2 Schlücke.", category: "classic" },
  { text: "Wer noch nie den Nachtzug genommen hat: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal beim Versuch, jemanden zu beeindrucken, gestolpert ist: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal beim Trampen mitgenommen wurde: 3 Schlücke.", category: "classic" },
  { text: "Wer schon mal die falsche SIM-Karte in sein Handy eingesteckt hat: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal einem Fremden die Tür aufgehalten und dann ewig gewartet hat: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal eine Hose angezogen hat, die plötzlich nicht mehr gepasst hat: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal an einem 0-Grad-Tag draußen gegessen hat: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal auf einer Geburtstagskarte den Namen falsch geschrieben hat: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal vergessen hat, ein Paket abzuholen: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal beim Aufwachen nicht gewusst hat, wo er ist: 2 Schlücke.", category: "classic" },
  { text: "Wer noch nie Blut gespendet hat: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal beim Heimweg den Schlüssel nicht gefunden hat: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal beim Fotoschießen aus Versehen ein Video gestartet hat: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal beim Hochladen eines Fotos das falsche genommen hat: 2 Schlücke.", category: "classic" },
  { text: "Wer schon mal einen Witz nicht verstanden hat und trotzdem gelacht hat: 1 Schluck.", category: "classic" },
  { text: "Wer schon mal bei Google Maps in die falsche Richtung gefahren ist: 2 Schlücke.", category: "classic" },
  { text: "Der/Die Vorlesende verteilt 4 Schlücke an wen auch immer er/sie möchte.", category: "action" },
  { text: "Reihum Länder nennen, die mit 'S' beginnen. Wer hängt, trinkt 2.", category: "action" },
  { text: "Alle, die heute schon etwas gegessen haben, das nicht zu Hause zubereitet wurde: 1 Schluck.", category: "action" },
  { text: "Schere-Stein-Papier: alle spielen gleichzeitig gegen die Person links. Verlierer trinken 2.", category: "action" },
  { text: "Alle strecken gleichzeitig eine Zahl von 1 bis 5 aus. Wer alleine steht, verteilt 3 Schlücke.", category: "action" },
  { text: "Reihum Disney-Filme nennen. Wer hängt, trinkt 2.", category: "action" },
  { text: "Wer als Letztes aufsteht und sich dreht, trinkt 2.", category: "action" },
  { text: "Alle zeigen gleichzeitig Daumen hoch oder runter. Minderheit trinkt 2.", category: "action" },
  { text: "Reihum Berufe mit 'L' nennen. Wer hängt, trinkt 2.", category: "action" },
  { text: "Alle zeigen gleichzeitig, wie viele Finger sie wollen. Wer alleine steht, trinkt 3.", category: "action" },
  { text: "Der/Die Vorlesende singt 10 Sekunden – oder trinkt 3.", category: "action" },
  { text: "Reihum Superhelden nennen. Wer hängt oder sich wiederholt, trinkt 2.", category: "action" },
  { text: "Alle tippen gleichzeitig auf eine Person. Wer die meisten Stimmen bekommt, verteilt 3.", category: "action" },
  { text: "Wer als Letztes beide Hände auf den Tisch legt, trinkt 2.", category: "action" },
  { text: "Reihum Tiere mit langen Hälsen nennen. Wer hängt: 3 Schlücke.", category: "action" },
  { text: "Alle halten gleichzeitig ihr Handy hoch. Wer das älteste Modell hat (Abstimmung), trinkt 2.", category: "action" },
  { text: "Der/Die Vorlesende macht 10 Kniebeugen oder trinkt 3.", category: "action" },
  { text: "Reihum Länder nennen, die ans Meer grenzen. Wer hängt, trinkt 2.", category: "action" },
  { text: "Alle sagen gleichzeitig ein Tier. Wer das exotischste nennt (Abstimmung): verteilt 3.", category: "action" },
  { text: "Wer als Letztes 'Prost' auf Türkisch sagt (Şerefe!): trinkt 2.", category: "action" },
  { text: "Reihum Dinge in einer Küche nennen. Wer hängt, trinkt 2.", category: "action" },
  { text: "Alle zeigen gleichzeitig auf jemanden. Wer die meisten Finger zeigt, verteilt 4.", category: "action" },
  { text: "Der/Die Vorlesende imitiert ein Tier – Runde rät. Wird's nicht erraten: 2 für die Runde.", category: "action" },
  { text: "Reihum Fußball-Nationalmannschaften nennen. Wer hängt, trinkt 2.", category: "action" },
  { text: "Alle schließen die Augen. Wer als Erstes wieder aufmacht, trinkt 2.", category: "action" },
  { text: "Der/Die Vorlesende sagt einen Zungenbrecher. Patzt er/sie: 2 Schlücke.", category: "action" },
  { text: "Reihum Früchte mit mehr als 5 Buchstaben nennen. Wer hängt, trinkt 2.", category: "action" },
  { text: "Alle strecken gleichzeitig die Zunge raus. Wer zuletzt: trinkt 2.", category: "action" },
  { text: "Wer das kürzeste Wort auf seinem Handy-Bildschirm findet (30 Sek), verteilt 3.", category: "action" },
  { text: "Reihum Getränke-Marken nennen. Wer hängt, trinkt 2.", category: "action" },
  { text: "Alle sagen gleichzeitig eine Zahl 1-20. Wer am nächsten an 13 ist, verteilt 3.", category: "action" },
  { text: "Alle winken gleichzeitig. Wer zuletzt: trinkt 2.", category: "action" },
  { text: "Reihum Bundesländer nennen. Wer hängt oder falsch liegt, trinkt 2.", category: "action" },
  { text: "Der/Die Vorlesende macht 15 Sekunden Liegestütz oder trinkt 3.", category: "action" },
  { text: "Wer als Letztes aufzeigt, wenn gefragt wird wer schon mal im Ausland war, trinkt 1.", category: "action" },
  { text: "Alle beatboxen 5 Sekunden gleichzeitig. Wer aufhört, trinkt 2.", category: "action" },
  { text: "Reihum Dinge nennen, die in einem Rucksack sind. Wer hängt, trinkt 2.", category: "action" },
  { text: "Der/Die Vorlesende wählt: selbst 3 trinken oder eine Runde ausgeben (5 Schlücke verteilen).", category: "action" },
  { text: "Reihum Schauspieler und Schauspielerinnen nennen. Wer hängt, trinkt 2.", category: "action" },
  { text: "Alle halten die Luft an. Wer als Erstes aufgibt, trinkt 2.", category: "action" },
  { text: "Wer sein Handy in unter 5 Sekunden entsperrt, verteilt 2. Sonst trinkt er/sie 2.", category: "action" },
  { text: "Reihum Dinge nennen, die rot sind. Wer hängt oder sich wiederholt, trinkt 2.", category: "action" },
  { text: "Alle sagen gleichzeitig ein Wort mit 'sch'. Wer dasselbe wie jemand anderem sagt, trinkt 2.", category: "action" },
  { text: "Der/Die Vorlesende macht einen Handstand oder trinkt 4.", category: "action" },
  { text: "Reihum Vornamen mit 'M' nennen. Wer hängt, trinkt 2.", category: "action" },
  { text: "Alle klatschen gleichzeitig. Wer am lautesten (Abstimmung): verteilt 3.", category: "action" },
  { text: "Wer als Letztes aufsteht und die Arme hebt, trinkt 2.", category: "action" },
  { text: "Reihum Sprachen nennen. Wer hängt, trinkt 2.", category: "action" },
  { text: "Alle flüstern gleichzeitig ihr Lieblingsessen. Wer am lautesten flüstert (Abstimmung), trinkt 2.", category: "action" },
  { text: "Reihum Dinge im Raum beschreiben. Wer's nicht schafft, trinkt 2.", category: "action" },
  { text: "Der/Die Vorlesende bestimmt: alle trinken 1 oder niemand trinkt – Mehrheitsentscheidung.", category: "action" },
  { text: "Reihum Köche oder Köchinnen aus TV-Shows nennen. Wer hängt, trinkt 2.", category: "action" },
  { text: "Alle stellen sich auf ein Bein. Wer als Erstes umfällt, trinkt 3.", category: "action" },
  { text: "Wer die längsten Haare hat (Abstimmung), darf 2 Schlücke verteilen.", category: "action" },
  { text: "Reihum Sportarten ohne Ball nennen. Wer hängt, trinkt 2.", category: "action" },
  { text: "Alle zeigen gleichzeitig ihre Schuhe. Wer die buntesten hat (Abstimmung): verteilt 3.", category: "action" },
  { text: "Der/Die Vorlesende erzählt in 15 Sekunden eine erfundene Geschichte. Glaubt's jemand: er/sie verteilt 3.", category: "action" },
  { text: "Reihum Wörter nennen, die mit 'un' beginnen. Wer hängt, trinkt 2.", category: "action" },
  { text: "Alle sagen gleichzeitig eine Jahreszahl 1900-2024. Gleiche Jahreszahlen trinken 2.", category: "action" },
  { text: "Wer als Letztes die Arme verschränkt, trinkt 2.", category: "action" },
  { text: "Reihum Hauptstädte in Asien nennen. Wer hängt, trinkt 2.", category: "action" },
  { text: "Alle legen gleichzeitig ihre Hände auf den Kopf. Wer zuletzt: trinkt 2.", category: "action" },
  { text: "Der/Die Vorlesende nennt eine Zahl 1–10. Wer am nächsten rät: verteilt 3.", category: "action" },
  { text: "Reihum Fast-Food-Ketten nennen. Wer hängt, trinkt 2.", category: "action" },
  { text: "Alle machen gleichzeitig ein Geräusch. Schönstes Geräusch (Abstimmung): verteilt 3.", category: "action" },
  { text: "Wer die meisten Nachrichten auf dem Handy hat (Schätzung, zeigen): verteilt 2.", category: "action" },
  { text: "Reihum Musikgenres nennen. Wer hängt, trinkt 2.", category: "action" },
  { text: "Alle schnipsen gleichzeitig. Wer es nicht schafft: trinkt 2.", category: "action" },
  { text: "Der/Die Vorlesende sagt ein Sprichwort. Ergänzt jemand es falsch: trinkt er/sie 2.", category: "action" },
  { text: "Reihum Dinge nennen, die man einfrieren kann. Wer hängt, trinkt 2.", category: "action" },
  { text: "Alle sagen gleichzeitig ihr Lieblingstier. Gleich wie jemand anderem: 1 Schluck, aber Fistbump.", category: "action" },
  { text: "Wer als Letztes seinen Namen buchstabiert (vorwärts und rückwärts), trinkt 2.", category: "action" },
  { text: "Reihum etwas Blaues im Raum benennen. Wer hängt, trinkt 2.", category: "action" },
  { text: "Alle machen gleichzeitig einen Herzschlag-Sound. Lautester (Abstimmung): verteilt 2.", category: "action" },
  { text: "Der/Die Vorlesende wählt zwei Personen für ein Schere-Stein-Papier-Match. Verlierer trinkt 3.", category: "action" },
  { text: "Reihum Dinge nennen, die man in einem Hotel findet. Wer hängt, trinkt 2.", category: "action" },
  { text: "Alle singen gleichzeitig die erste Zeile eines Songs. Wer aufhört: trinkt 2.", category: "action" },
  { text: "Wer das aktuellste Foto auf dem Handy hat (anzeigen), verteilt 3.", category: "action" },
  { text: "Reihum Schulfächer nennen. Wer hängt, trinkt 2.", category: "action" },
  { text: "Alle machen gleichzeitig Boxbewegungen. Langsamster (Abstimmung): trinkt 2.", category: "action" },
  { text: "Der/Die Vorlesende zählt in einer Fremdsprache bis 10. Patzt er/sie: 2 Schlücke.", category: "action" },
  { text: "Reihum Vornamen mit 'A' nennen. Wer hängt, trinkt 2.", category: "action" },
  { text: "Alle sagen gleichzeitig 'Cheers' in einer anderen Sprache. Gleiche Sprache wie jemand anderem: 1 Schluck.", category: "action" },
  { text: "Wer schon mal auf jemanden eifersüchtig war, ohne Grund: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal eine Unterhaltung über die Person abgebrochen, die gerade ankam: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal eine Dating-App benutzt hat, obwohl er/sie in einer Beziehung war: 4 Schlücke.", category: "spicy" },
  { text: "Wer schon mal jemanden gedatet hat, den seine Freunde nicht mochten: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal eine ernsthafte Beziehung aus Langeweile beendet hat: 3 Schlücke.", category: "spicy" },
  { text: "Wer schon mal auf jemanden gewartet hat, der gar nicht kommen wollte: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal mit jemandem geflirtet hat, nur um Aufmerksamkeit zu bekommen: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal nach dem Ausgehen jemanden mit nach Hause genommen hat: 3 Schlücke.", category: "spicy" },
  { text: "Wer schon mal jemanden geküsst hat, der/die vergeben war: 3 Schlücke.", category: "spicy" },
  { text: "Wer schon mal auf Tinder, Bumble oder Hinge geswiped hat: 1 Schluck.", category: "spicy" },
  { text: "Wer schon mal ein Date hatte, das so schlimm war, dass er/sie früher gegangen ist: 3 Schlücke.", category: "spicy" },
  { text: "Wer schon mal jemandem falsche Komplimente gemacht hat: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal beim Sex gelogen hat – über irgendwas: 2 Schlücke (still).", category: "spicy" },
  { text: "Wer schon mal nach einer Trennung sofort jemand Neues gefunden hat: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal wegen jemandem aus dieser Runde nervös war: 3 Schlücke.", category: "spicy" },
  { text: "Wer schon mal jemanden gezielt ignoriert hat, um Interesse zu wecken: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal eine Beziehung ernsthaft in Betracht gezogen hat, die nicht stattgefunden hat: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal mit dem Gedanken gespielt hat, jemanden aus der Runde zu daten: 3 Schlücke.", category: "spicy" },
  { text: "Wer schon mal einen Kuss bereut hat: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal jemandem eine Nachricht geschrieben hat und sie nicht abgesendet hat: 1 Schluck.", category: "spicy" },
  { text: "Wer schon mal jemanden ghostet hat, der/die es nicht verdient hatte: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal Stunden lang an jemandem getippt und die Nachricht dann gelöscht hat: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal jemanden geliked hat, um Aufmerksamkeit zu bekommen: 1 Schluck.", category: "spicy" },
  { text: "Wer schon mal bei einem Date so nervös war, dass er/sie kaum reden konnte: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal jemanden geküsst hat, den er/sie gar nicht so mochte: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal für jemanden geflogen ist oder eine lange Reise gemacht hat: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal eifersüchtig auf den Ex des Ex war: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal eine Nachricht auf dem Handy des Partners gelesen hat: 3 Schlücke.", category: "spicy" },
  { text: "Wer schon mal die Lieblingsband oder den Lieblingsfilm angepasst hat, um jemanden zu beeindrucken: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal jemanden bewusst eifersüchtig gemacht hat: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal beim Ausgehen gelogen hat, wo er/sie ist: 3 Schlücke.", category: "spicy" },
  { text: "Wer schon mal eine Beziehung beendet und es danach bereut hat: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal jemanden aus Mitleid gedatet hat: 3 Schlücke.", category: "spicy" },
  { text: "Wer schon mal eine Nacht mit jemandem verbracht hat, den er/sie nur einmal getroffen hat: 3 Schlücke.", category: "spicy" },
  { text: "Wer schon mal auf dem Profil einer Ex oder eines Ex gestöbert hat: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal absichtlich langsam auf Nachrichten geantwortet hat: 1 Schluck.", category: "spicy" },
  { text: "Wer schon mal beim Ausgehen jemanden angesprochen hat, der/die schon vergeben war: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal jemanden aus Gewohnheit statt Liebe gedatet hat: 3 Schlücke.", category: "spicy" },
  { text: "Wer schon mal einen Flirt angefangen und dann abgebrochen hat: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal so oft sein Handy gecheckt hat wie heute: 1 Schluck.", category: "spicy" },
  { text: "Wer schon mal jemanden gefragt hat, ob er/sie single ist – und es war nicht der Fall: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal auf der Hochzeit eines anderen geflirtet hat: 3 Schlücke.", category: "spicy" },
  { text: "Wer schon mal ein Bett mit jemandem geteilt hat – platonisch aber mit Gefühlen: 3 Schlücke.", category: "spicy" },
  { text: "Wer schon mal in jemanden verliebt war, der/die bereits mit dem/der besten Freund/in zusammen war: 4 Schlücke.", category: "spicy" },
  { text: "Wer schon mal ohne Grund aufgehört zu schreiben und jemanden stehen lassen hat: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal mit dem Ex geredet hat, ohne es dem/der aktuellen Partner/in zu sagen: 3 Schlücke.", category: "spicy" },
  { text: "Wer schon mal ein Foto gelikt hat, das Jahre alt war – absichtlich: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal jemanden angeschrieben hat, nur weil die andere Person aufgehört hatte zu schreiben: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal Sex auf einer Reise hatte – mit einer fremden Person: 3 Schlücke.", category: "spicy" },
  { text: "Wer schon mal eine Beziehung aufrechterhalten hat, nur weil man sich einen Schritt nicht getraut hat: 3 Schlücke.", category: "spicy" },
  { text: "Wer schon mal jemandem 'Ich liebe dich' gesagt hat ohne es so zu meinen: 4 Schlücke.", category: "spicy" },
  { text: "Wer schon mal auf einem Date heimlich aufs Handy geschaut hat: 1 Schluck.", category: "spicy" },
  { text: "Wer schon mal jemanden in der Runde heimlich angehimmelt hat: 3 Schlücke.", category: "spicy" },
  { text: "Wer schon mal jemandem den Namen des Ex mitgeteilt hat, ungefragt: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal eine Person aus dem Freundeskreis gedatet hat, die jetzt wieder nur 'Freund' ist: 3 Schlücke.", category: "spicy" },
  { text: "Wer schon mal Fotos eines/einer Ex aus Wut gelöscht und sie/ihn danach vermisst hat: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal mehr als 6 Monate Single war und es genossen hat: 1 Schluck.", category: "spicy" },
  { text: "Wer schon mal auf jemanden gewartet hat, der/die nie aufgetaucht ist: 3 Schlücke.", category: "spicy" },
  { text: "Wer schon mal jemandem nachgeschaut hat, obwohl er/sie in einer Beziehung war: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal eine Dating-App deinstalliert und am selben Tag neu installiert hat: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal beim Flirten peinlich auf die Nase gefallen ist: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal jemandem sein Passwort gegeben hat: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal Emotionen gespielt hat, die er/sie nicht hatte – in einer Beziehung: 3 Schlücke.", category: "spicy" },
  { text: "Wer schon mal jemanden wegen äußerlicher Merkmale abgelehnt hat: 2 Schlücke (ehrlich).", category: "spicy" },
  { text: "Wer schon mal etwas Wichtiges aufgegeben hat, das er/sie nie zurückbekommen hat: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal jemandem etwas gesagt hat, das er sofort bereut hat: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal geweint hat, ohne zu wissen warum: 1 Schluck.", category: "deep" },
  { text: "Wer schon mal mit einem Freund oder einer Freundin gestritten und nie wieder geredet hat: 3 Schlücke.", category: "deep" },
  { text: "Wer schon mal allein Entscheidungen getroffen hat, die er/sie mit anderen hätte teilen sollen: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal eine Chance nicht ergriffen hat und es bis heute bereut: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal jemandem vergeben hat, dem er/sie vielleicht nicht hätte vergeben sollen: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal wochenlang gebraucht hat, um aus dem Bett zu kommen: 3 Schlücke.", category: "deep" },
  { text: "Wer schon mal den Kontakt zu einer nahestehenden Person verloren hat und nicht mehr weiß warum: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal etwas erreicht hat, das er/sie früher für unmöglich hielt: 1 Schluck – Glückwunsch.", category: "deep" },
  { text: "Wer schon mal sich selbst so verloren hat, dass er/sie sich kaum wiedererkannt hat: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal bei jemandem Trost gesucht hat, der/die selbst Hilfe brauchte: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal etwas gesagt hat, das eine Beziehung für immer verändert hat: 3 Schlücke.", category: "deep" },
  { text: "Wer schon mal für jemanden stark sein musste, obwohl er/sie selbst litt: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal eine lange Phase hatte, in der er/sie sich sehr allein gefühlt hat: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal über das Leben eines anderen nachgedacht hat und sich gefragt hat, wie es wäre: 1 Schluck.", category: "deep" },
  { text: "Wer schon mal eine Therapiesitzung hatte, die alles verändert hat: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal jemandem etwas Wichtiges verschwiegen hat, um ihn/sie zu schützen: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal eine Entscheidung getroffen hat, die andere für falsch hielten – und es sich ausgezahlt hat: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal so müde war, dass er/sie aufgehört hat, um Dinge zu kämpfen, die ihm/ihr wichtig waren: 3 Schlücke.", category: "deep" },
  { text: "Wer schon mal bei einer Beerdigung gesprochen hat: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal jemanden so sehr vermisst hat, dass es körperlich wehtat: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal eine wichtige Freundschaft verloren hat und bis heute nicht ganz darüber hinweg ist: 3 Schlücke.", category: "deep" },
  { text: "Wer schon mal für jemanden eine große Lüge erzählt hat: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal jemanden um Entschuldigung gebeten hat, ohne wirklich zu wissen, ob es reicht: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal jemandem 'Es geht mir gut' gesagt hat, obwohl das weit von der Wahrheit war: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal in einem Moment realisiert hat, dass eine Freundschaft vorbei ist – ohne Streit: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal auf etwas gehofft hat, das nie passiert ist: 1 Schluck.", category: "deep" },
  { text: "Wer schon mal jemanden um Hilfe bitten wollte und es nicht geschafft hat: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal eine toxische Freundschaft oder Beziehung zu lange aufrechterhalten hat: 3 Schlücke.", category: "deep" },
  { text: "Wer schon mal eine persönliche Grenze überschritten und es erst danach gemerkt hat: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal ein Geheimnis verraten hat, das nicht seines/ihres war: 3 Schlücke.", category: "deep" },
  { text: "Wer schon mal vor etwas Angst hatte, das die anderen für selbstverständlich halten: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal jemanden an die erste Stelle gesetzt hat, bei dem er/sie nicht an erster Stelle stand: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal eine Entscheidung bereut, die er/sie für die Karriere getroffen hat: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal etwas über sich selbst herausgefunden hat, das ihn/sie erschreckt hat: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal gelernt hat, loszulassen – und es danach wirklich besser war: 1 Schluck.", category: "deep" },
  { text: "Wer schon mal jemanden nicht mehr in seinem Leben haben wollte und es trotzdem nicht gesagt hat: 3 Schlücke.", category: "deep" },
  { text: "Wer schon mal auf etwas verzichtet hat, das er/sie liebte, für jemanden anderen: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal mehr für jemanden gefühlt hat, als derjenige für ihn/sie: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal jemandem nachgelaufen ist, der/die sich nicht gemeldet hat: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal in einer Phase gelebt hat, über die er/sie nie redet: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal eine lange Freundschaft von einem Tag auf den anderen abgebrochen hat: 3 Schlücke.", category: "deep" },
  { text: "Wer schon mal jemanden verloren hat, ohne sich richtig zu verabschieden: 3 Schlücke.", category: "deep" },
  { text: "Wer schon mal eine Entscheidung getroffen hat und seitdem ein anderes Leben führt: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal jemanden so sehr geliebt hat, dass es ihn/sie kaputt gemacht hat: 3 Schlücke.", category: "deep" },
  { text: "Wer schon mal etwas Wichtiges zu spät gesagt hat: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal in einer Krise war und erst danach gemerkt hat, wer wirklich da war: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal eine Version von sich selbst vermisst hat: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal etwas Gutes für jemanden getan hat und dafür nie Dank bekommen hat: 1 Schluck.", category: "deep" },
  { text: "Wer schon mal einem Elternteil etwas verschwiegen hat, das er/sie bis heute nicht wissen: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal gezweifelt hat, ob er/sie den richtigen Weg eingeschlagen hat: 1 Schluck.", category: "deep" },
  { text: "Wer schon mal jemandem geschrieben hat, der/die nicht mehr lebt: 3 Schlücke.", category: "deep" },
  { text: "Wer schon mal bereut, dass er/sie früher nicht mutiger war: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal für jemanden gebetet oder Kraft geschickt hat, obwohl er/sie es nicht zeigt: 1 Schluck.", category: "deep" },
  { text: "Wer schon mal in einer Situation war, die ihn/sie für immer verändert hat: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal versucht hat, ein anderes Leben zu führen, und es nicht durchgehalten hat: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal wegen jemandem geweint hat, ohne dass dieser es weiß: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal jemandem gezeigt hat, wie sehr er/sie ihn/sie braucht – und es schmerzte: 3 Schlücke.", category: "deep" },
  { text: "Wer schon mal entschieden hat, sich selbst an erste Stelle zu setzen – und es war schwer: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal etwas so sehr gewollt hat, dass es ihn/sie jeden Tag beschäftigt hat: 1 Schluck.", category: "deep" },
  { text: "Wer schon mal ein Detail über sich selbst verraten hat, das er/sie sofort bereut hat: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal zugegeben hat, dass er/sie falsch lag – und es war befreiend: 1 Schluck.", category: "deep" },
  { text: "Wer schon mal eine Entscheidung getroffen hat, die andere für egoistisch hielten, aber richtig war: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal jemanden um Entschuldigung gebeten hat, den/die er/sie nie mehr gesehen hat: 3 Schlücke.", category: "deep" },
  { text: "Wer schon mal jemanden um seine Meinung gebeten hat und sie nicht hören wollte: 1 Schluck.", category: "deep" },
  { text: "Wer schon mal aufgehört hat, sich zu erklären – und es war die beste Entscheidung: 1 Schluck.", category: "deep" },
  { text: "Wer schon mal Angst vor dem eigenen Erfolg hatte: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal der Grund für das Lächeln eines anderen war, ohne es zu wissen: 1 Schluck.", category: "deep" },
  { text: "Wer schon mal jemanden fest umarmt hat, weil er/sie wusste, es könnte das letzte Mal sein: 3 Schlücke.", category: "deep" },


  { text: "Reihum Länder in Afrika nennen. Wer hängt, trinkt 2.", category: "action" },
  { text: "Alle klopfen gleichzeitig auf den Tisch. Wer aufhört: trinkt 2.", category: "action" },
  { text: "Der/Die Vorlesende wählt: Wahrheit oder 3 Schlücke.", category: "action" },
  { text: "Reihum Dinge nennen, die man am Strand findet. Wer hängt, trinkt 2.", category: "action" },
  { text: "Alle machen gleichzeitig ein Vogel-Geräusch. Bestes (Abstimmung): verteilt 3.", category: "action" },
  { text: "Wer als Letztes aufzeigt, wenn die Frage kommt, trinkt 1.", category: "action" },
  { text: "Reihum Berufe nennen, die mit Uniform verbunden sind. Wer hängt, trinkt 2.", category: "action" },
  { text: "Alle strecken gleichzeitig die rechte Hand aus. Wer zuletzt: trinkt 2.", category: "action" },
  { text: "Der/Die Vorlesende flüstert jemandem etwas ins Ohr – dieser muss es nacherzählen.", category: "action" },
  { text: "Reihum Dinge nennen, die man in einem Büro findet. Wer hängt, trinkt 2.", category: "action" },
  { text: "Alle machen gleichzeitig eine Tanzbewegung. Ausgefallenste (Abstimmung): verteilt 3.", category: "action" },
  { text: "Wer als Letztes lacht, wenn jemand einen Witz erzählt, trinkt 2.", category: "action" },
  { text: "Reihum Länder in Südamerika nennen. Wer hängt, trinkt 2.", category: "action" },
  { text: "Alle sagen gleichzeitig einen Monat. Gleicher Monat wie jemand anderem: 1 Schluck.", category: "action" },
  { text: "Der/Die Vorlesende macht eine Grimasse – alle müssen sie kopieren. Wer zuletzt: trinkt 2.", category: "action" },
  { text: "Reihum Dinge nennen, die leuchten. Wer hängt, trinkt 2.", category: "action" },
  { text: "Alle zeigen gleichzeitig ihre Socken. Bunteste (Abstimmung): verteilt 2.", category: "action" },
  { text: "Wer als Letztes sein Glas hebt, trinkt 2.", category: "action" },
  { text: "Reihum Instrumente nennen. Wer hängt oder sich wiederholt, trinkt 2.", category: "action" },
  { text: "Alle machen gleichzeitig einen Moonwalk-Versuch. Bester (Abstimmung): verteilt 3.", category: "action" },
  { text: "Der/Die Vorlesende nennt eine Farbe – alle zeigen sofort etwas in dieser Farbe. Letzte:r trinkt 2.", category: "action" },
  { text: "Reihum Dinge nennen, die sich gut anfühlen. Wer hängt, trinkt 2.", category: "action" },
  { text: "Alle halten gleichzeitig ihren Atem an und zählen. Wer am längsten durchhält: verteilt 3.", category: "action" },
  { text: "Wer als Letztes aufsteht und einen Stern macht, trinkt 2.", category: "action" },
  { text: "Reihum Dinge nennen, die süß riechen. Wer hängt, trinkt 2.", category: "action" },
  { text: "Alle tippen gleichzeitig eine Zahl 1-100 in ihr Handy. Wer am nächsten an 50 ist, verteilt 3.", category: "action" },
  { text: "Der/Die Vorlesende imitiert eine berühmte Person – Runde rät. Nicht erraten: alle trinken 1.", category: "action" },
  { text: "Reihum Wörter nennen, die 'Nacht' enthalten. Wer hängt, trinkt 2.", category: "action" },
  { text: "Alle sagen gleichzeitig 'ich mag'. Gleicher Begriff wie jemand anderem: beide trinken 1.", category: "action" },
  { text: "Wer als Letztes beide Augen zukneift, trinkt 2.", category: "action" },
  { text: "Reihum Dinge nennen, die man in einem Zug findet. Wer hängt, trinkt 2.", category: "action" },
  { text: "Alle machen gleichzeitig die Arme weit auf. Wer am weitesten aufmacht (Schätzung): verteilt 2.", category: "action" },
  { text: "Der/Die Vorlesende zählt rückwärts von 20 auf 1. Fehler: 2 Schlücke.", category: "action" },
  { text: "Reihum Dinge nennen, die kalt sind. Wer hängt, trinkt 2.", category: "action" },
  { text: "Alle zeigen gleichzeitig ihre Lieblingsapp. Seltenste (Abstimmung): verteilt 3.", category: "action" },
  { text: "Wer als Letztes laut 'Ja!' ruft, trinkt 2.", category: "action" },
  { text: "Reihum Dinge nennen, die man in einem Supermarkt kaufen kann aber selten kauft. Wer hängt, trinkt 2.", category: "action" },
  { text: "Alle machen gleichzeitig Klatschgeräusche – lauter und lauter. Wer aufhört: trinkt 2.", category: "action" },
  { text: "Der/Die Vorlesende sagt 5 Wörter rückwärts buchstabieren. Fehler: 2 Schlücke.", category: "action" },
  { text: "Reihum Dinge nennen, die rund sind. Wer hängt, trinkt 2.", category: "action" },
  { text: "Alle wackeln gleichzeitig mit den Ohren. Wer es schafft (Abstimmung): verteilt 2. Schafft es niemand: alle trinken 1.", category: "action" },
  { text: "Wer als Letztes seinen Lieblingsfilm nennt, trinkt 2.", category: "action" },
  { text: "Reihum Dinge nennen, die man zum Campen braucht. Wer hängt, trinkt 2.", category: "action" },
  { text: "Alle zeigen gleichzeitig, wie sie tanzen. Siftigster Tanz (Abstimmung): verteilt 3.", category: "action" },
  { text: "Der/Die Vorlesende sagt ein Wort auf Englisch – alle müssen es auf Deutsch sagen. Wer am langsamsten: 2.", category: "action" },
  { text: "Reihum Dinge nennen, die man im Winter anzieht. Wer hängt, trinkt 2.", category: "action" },
  { text: "Alle drehen sich gleichzeitig einmal im Kreis. Wer am schönsten dreht (Abstimmung): verteilt 2.", category: "action" },
  { text: "Wer als Letztes auf sein Handy schaut, trinkt 2.", category: "action" },
  { text: "Reihum Dinge nennen, die man in einer Schule braucht. Wer hängt, trinkt 2.", category: "action" },
  { text: "Alle sagen gleichzeitig 'Nein'. Überzeugendste:r (Abstimmung): verteilt 3.", category: "action" },
  { text: "Der/Die Vorlesende beschreibt einen Film in 3 Wörtern. Errät die Runde ihn nicht: alle trinken 1.", category: "action" },
  { text: "Reihum Dinge nennen, die fliegen können. Wer hängt, trinkt 2.", category: "action" },
  { text: "Alle tippen gleichzeitig in die Luft wie auf einer Tastatur. Schnellste:r (Abstimmung): verteilt 2.", category: "action" },
  { text: "Wer als Letztes die Zunge rausstreckt, trinkt 2.", category: "action" },
  { text: "Reihum Dinge nennen, die man aus Holz macht. Wer hängt, trinkt 2.", category: "action" },
  { text: "Alle sagen gleichzeitig einen Wochentag. Gleicher Wochentag: beide trinken 1.", category: "action" },
  { text: "Der/Die Vorlesende macht 20 Sekunden Planke oder trinkt 3.", category: "action" },
  { text: "Reihum Dinge nennen, die man im Dunkeln sehen kann. Wer hängt, trinkt 2.", category: "action" },
  { text: "Alle machen gleichzeitig einen Frosch-Sprung. Weiteste:r (Abstimmung): verteilt 3.", category: "action" },
  { text: "Wer als Letztes lächelt wenn die Person links lächelt, trinkt 2.", category: "action" },
  { text: "Reihum Dinge nennen, die man aus Glas macht. Wer hängt, trinkt 2.", category: "action" },
  { text: "Alle sagen gleichzeitig eine Jahreszahl aus dem letzten Jahrhundert. Nächste an 1969: verteilt 3.", category: "action" },
  { text: "Der/Die Vorlesende erklärt einem Alien in 15 Sek was ein Handy ist. Überzeugendste Erklärung: verteilt 2.", category: "action" },
  { text: "Reihum Dinge nennen, die man mit Wasser macht. Wer hängt, trinkt 2.", category: "action" },
  { text: "Alle zeigen gleichzeitig ihre älteste App. Längste installiert (Abstimmung): verteilt 3.", category: "action" },
  { text: "Wer als Letztes 'Cheers' auf Japanisch sagt (Kanpai!): trinkt 2.", category: "action" },
  { text: "Reihum Dinge nennen, die man mit Feuer macht. Wer hängt, trinkt 2.", category: "action" },
  { text: "Alle sagen gleichzeitig einen Körperteil. Witzigster (Abstimmung): verteilt 2.", category: "action" },
  { text: "Der/Die Vorlesende denkt an eine berühmte Person – alle stellen Ja/Nein-Fragen. Wer es nicht errät in 5 Fragen: 2 Schlücke.", category: "action" },
  { text: "Reihum Dinge nennen, die man in einem Krankenhaus findet. Wer hängt, trinkt 2.", category: "action" },
  { text: "Alle machen gleichzeitig ihren besten Roboter-Move. Überzeugendste:r (Abstimmung): verteilt 3.", category: "action" },
  { text: "Wer als Letztes aufzeigt, trinkt 2.", category: "action" },
  { text: "Reihum Dinge nennen, die schwer sind. Wer hängt, trinkt 2.", category: "action" },
  { text: "Alle sagen gleichzeitig 'Ich bin...' und ergänzen es. Überraschendste Aussage (Abstimmung): verteilt 2.", category: "action" },
  { text: "Der/Die Vorlesende erklärt in Pantomime ein Wort. Runde rät – nicht erraten in 10 Sek: alle trinken 1.", category: "action" },
  { text: "Reihum Dinge nennen, die klein sind aber wichtig. Wer hängt, trinkt 2.", category: "action" },
  { text: "Alle zeigen gleichzeitig wie sie ausssehen, wenn sie aufwachen. Echteste Darstellung (Abstimmung): verteilt 2.", category: "action" },
  { text: "Wer als Letztes einen Stern mit dem Finger in die Luft zeichnet, trinkt 2.", category: "action" },
  { text: "Reihum Dinge nennen, die man in einer Apotheke kauft. Wer hängt, trinkt 2.", category: "action" },
  { text: "Alle sagen gleichzeitig einen Satz mit genau 5 Wörtern. Beste:r (Abstimmung): verteilt 2.", category: "action" },
  { text: "Der/Die Vorlesende gibt jemandem ein Kompliment. Die Person muss es so gut wie möglich weitergeben. Wer stoppt: trinkt 2.", category: "action" },
  { text: "Reihum Dinge nennen, die grün sind. Wer hängt oder sich wiederholt, trinkt 2.", category: "action" },
  { text: "Alle machen gleichzeitig eine Yoga-Pose. Ausgefallenste (Abstimmung): verteilt 3.", category: "action" },
  { text: "Wer als Letztes klatscht, trinkt 2.", category: "action" },
  { text: "Reihum Länder nennen, in denen man kein Visum braucht. Wer falsch liegt, trinkt 2.", category: "action" },
  { text: "Alle sagen gleichzeitig ihre Schuhgröße. Gleiche Größe: beide stoßen an.", category: "action" },
  { text: "Der/Die Vorlesende sagt ein deutsches Wort – alle übersetzen es gleichzeitig ins Englische. Falsch: 1 Schluck.", category: "action" },
  { text: "Reihum Dinge nennen, die man aus Leder macht. Wer hängt, trinkt 2.", category: "action" },
  { text: "Alle machen gleichzeitig ihren besten Opernsänger. Dramatischste:r (Abstimmung): verteilt 3.", category: "action" },
  { text: "Wer als Letztes auf den Tisch klopft, trinkt 2.", category: "action" },
  { text: "Wer schon mal jemanden durch eine gemeinsame Playlist verloren hat: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal mehr als einmal denselben Fehler in einer Beziehung gemacht hat: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal jemanden aus der Arbeit oder Schule gedatet hat: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal auf ein Date gegangen ist, nur weil er/sie nichts Besseres zu tun hatte: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal jemandem das Passwort seines Social-Media-Kontos gegeben hat: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal mehr als 5 aktive Chats gleichzeitig hatte: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal das Datum oder die Uhrzeit für ein Date vergessen hat: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal jemanden bewusst länger warten lassen hat beim Antworten: 1 Schluck.", category: "spicy" },
  { text: "Wer schon mal ein Rendezvous aus Nervosität abgesagt hat: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal auf einer Hochzeitsfeier getanzt hat und dabei zu weit gegangen ist: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal jemanden über Social Media kennengelernt und sich dann im echten Leben getroffen hat: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal nach dem ersten Kuss direkt gegangen ist: 3 Schlücke.", category: "spicy" },
  { text: "Wer schon mal 'Ich liebe dich' als Erster/Erste gesagt hat: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal ein Foto von jemandem geliked hat, das mehr als 3 Jahre alt war: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal jemandem eine Nachricht geschrieben hat, um zu sehen ob er/sie antwortet: 1 Schluck.", category: "spicy" },
  { text: "Wer schon mal aus einem Date eine Freundschaft gemacht hat: 1 Schluck.", category: "spicy" },
  { text: "Wer schon mal mehr als 3 Monate gebraucht hat, um über jemanden hinwegzukommen: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal ein Geheimnis über jemanden aus der Runde erfahren hat: 2 Schlücke (still).", category: "spicy" },
  { text: "Wer schon mal beim Ausgehen die Handynummer von jemandem bekommen und nie angeschrieben hat: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal bei einer Trennung erleichtert war: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal für jemanden auf etwas verzichtet hat, der/die es nicht wert war: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal einen Korb bekommen hat: 1 Schluck – du bist nicht allein.", category: "spicy" },
  { text: "Wer schon mal dem/der Ex der/des Ex begegnet ist: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal jemanden angeschrieben hat, nur weil es Nacht war und er/sie allein: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal beim Ausgehen jemanden geküsst hat, den/die er/sie danach nie wiedergesehen hat: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal eine Beziehung lieber per Schweigen als per Gespräch beendet hat: 3 Schlücke.", category: "spicy" },
  { text: "Wer schon mal auf einer Party heimlich auf jemanden aufmerksam gemacht hat: 1 Schluck.", category: "spicy" },
  { text: "Wer schon mal geweint hat, nachdem er/sie Schluss gemacht hat – obwohl er/sie selbst Schluss gemacht hat: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal Urlaubsbekanntschaft gemacht hat: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal beim Essen mit jemandem festgestellt hat, dass es kein Date war: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal auf Seiten des Ex gelacht hat und sich danach schlecht gefühlt hat: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal jemanden auf Wunsch eines anderen ignoriert hat: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal seinen/ihren Beziehungsstatus als 'Es ist kompliziert' geführt hat: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal jemandem gesagt hat, er/sie sei 'nur Freunde', obwohl das nicht ganz stimmte: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal jemanden angelogen, um aus einem Date herauszukommen: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal eine Dating-App-Biografie gefunden hat, die zu gut klang um wahr zu sein – und es war so: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal beim Ansehen von romantischen Filmen an eine konkrete Person gedacht hat: 1 Schluck.", category: "spicy" },
  { text: "Wer schon mal bei einem Blind Date sofort wusste, dass es nichts wird: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal den ersten Kuss an einem öffentlichen Ort erlebt hat: 1 Schluck.", category: "spicy" },
  { text: "Wer schon mal jemandem gesagt hat 'Du bist wie ein Bruder/eine Schwester' – und es ernst meinte: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal beim Sex über etwas anderes nachgedacht hat: 2 Schlücke (still).", category: "spicy" },
  { text: "Wer schon mal jemanden abgelenkt hat, um selbst etwas zu tun: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal eine Notlüge auf einem Date erzählt hat: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal jemandem im Streit gesagt hat, was er/sie nicht sagen wollte: 3 Schlücke.", category: "spicy" },
  { text: "Wer schon mal eine Playlist für jemanden erstellt hat: 1 Schluck.", category: "spicy" },
  { text: "Wer schon mal so verliebt war, dass er/sie nicht schlafen konnte: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal jemanden geküsst hat und kurz danach mit dem/der besten Freund/in darüber geredet hat: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal auf einem Dating-Profil etwas leicht übertrieben hat: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal jemanden zurückschreiben lassen, obwohl er/sie keine Antwort wollte: 1 Schluck.", category: "spicy" },
  { text: "Wer schon mal jemanden zufällig auf dem Klo eines Clubs getroffen und geküsst hat: 3 Schlücke.", category: "spicy" },
  { text: "Wer schon mal mit jemandem in einer Fremdsprache geflirtet hat: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal ein Date abgebrochen hat, weil die Chemie nicht stimmte: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal jemandem gesagt hat, er/sie solle sicherer sein – und selbst das Gegenteil: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal jemandem eine Schnullermeldung geschickt hat und es danach gelöscht hat: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal in einer Beziehung angefangen zu haben und dann gemerkt hat, es geht nicht: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal bei einem Date falsch buchstabiert hat und sich danach geschämt hat: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal auf dem Rückweg von einem misslungenen Date einen unerwarteten Kuss erhalten hat: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal jemanden bewundert hat, ohne ihm/ihr zu zeigen warum: 1 Schluck.", category: "spicy" },
  { text: "Wer schon mal jemandem ein Flirt-GIF geschickt hat: 1 Schluck.", category: "spicy" },
  { text: "Wer schon mal jemanden per Sprachnachricht beendet hat: 3 Schlücke.", category: "spicy" },
  { text: "Wer schon mal absichtlich eine unklare Antwort gegeben hat, um sich alle Optionen offen zu halten: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal mehr als 5 Personen gleichzeitig angeschrieben hat: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal jemanden als Backup gehalten hat: 3 Schlücke.", category: "spicy" },
  { text: "Wer schon mal jemanden um 3 Uhr morgens angeschrieben hat: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal auf einem First-Date schon den zweiten geplant hat: 1 Schluck.", category: "spicy" },
  { text: "Wer schon mal bemerkt hat, dass jemand Interesse hat, und so getan hat, als würde er/sie es nicht merken: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal auf einem Date zu früh 'Ich will Kinder' erwähnt hat: 3 Schlücke.", category: "spicy" },
  { text: "Wer schon mal mit jemandem aus der Gruppe geflirtet hat, ohne dass es jemand wusste: 3 Schlücke.", category: "spicy" },
  { text: "Wer schon mal jemanden um eine zweite Chance gebeten hat: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal auf einem Date Bilder vom Ex auf dem Handy des anderen gesehen hat: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal mit jemandem zusammen war, der/die jünger als 3 Jahre alt war als sie: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal zu schnell 'Es tut mir leid' gesagt hat, ohne es wirklich zu meinen: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal auf dem Handy des Partners/der Partnerin surfen durfte und es nicht getan hat, obwohl er/sie wollte: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal für jemanden eine Reise abgebrochen hat: 3 Schlücke.", category: "spicy" },
  { text: "Wer schon mal jemanden heiraten wollte und es dann nicht getan hat: 3 Schlücke.", category: "spicy" },
  { text: "Wer schon mal beim ersten Treffen zu viel von sich erzählt hat: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal jemanden gefragt hat 'Liebst du mich noch?' – und die Antwort war nicht die richtige: 3 Schlücke.", category: "spicy" },
  { text: "Wer schon mal Fotos eines One-Night-Stands noch auf dem Handy hat: 3 Schlücke.", category: "spicy" },
  { text: "Wer schon mal beim Ausgehen für jemanden anderen bezahlt hat, der/die es nie zurückgezahlt hat: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal mit dem Gedanken gespielt hat, jemanden vom Freundeskreis zu küssen: 3 Schlücke.", category: "spicy" },
  { text: "Wer schon mal auf einer Party zu jemandem gesagt hat 'Wo warst du die ganze Zeit?': 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal nach einem Streit auf Abstand gegangen ist, obwohl er/sie wollte, dass die andere Person näherkam: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal 'Ich bin nicht eifersüchtig' gesagt hat und trotzdem war: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal für jemanden aufgehört hat, mit einem Freund/einer Freundin zu hängen: 3 Schlücke.", category: "spicy" },
  { text: "Wer schon mal jemandem gesagt hat 'Ich finde dich attraktiv' ohne Kontext: 3 Schlücke.", category: "spicy" },
  { text: "Wer schon mal auf einem Date das Essen für den anderen bestellt hat, weil er/sie es besser wusste: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal jemandem heimlich etwas Liebes hinterlassen hat: 1 Schluck.", category: "spicy" },
  { text: "Wer schon mal jemanden per Social Media blockiert und entblockt hat, mehrfach: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal aus einer Beziehung ausgestiegen ist, weil die Eltern dagegen waren: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal auf jemanden gewartet hat, der/die nie 'Ich mag dich' sagen konnte: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal Interesse vorgespielt hat, um jemand anderen eifersüchtig zu machen: 3 Schlücke.", category: "spicy" },
  { text: "Wer schon mal jemandem 'Ich schreibe gleich wieder' gesagt und dann 3 Tage gebraucht hat: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal mit mehr als 3 Personen gleichzeitig etwas 'Undefiniertes' gehabt hat: 3 Schlücke.", category: "spicy" },
  { text: "Wer schon mal beim Date angefangen hat über den Ex zu sprechen: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal heimlich im Profil eines Schwarms nachgeschaut, ob er/sie jemanden gut kennt: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal eine Beziehung begonnen hat, obwohl er/sie wusste, es wird nicht gut gehen: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal auf einem Date eine andere Person attraktiver gefunden als sein/ihr Date: 3 Schlücke.", category: "spicy" },
  { text: "Wer schon mal jemanden aus dem Freundeskreis an jemand anderen verkuppelt hat und es bereut hat: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal mit jemandem ins Kino gegangen ist und keinen Film gesehen hat: 3 Schlücke.", category: "spicy" },
  { text: "Wer schon mal nach einer Trennung sofort einen neuen Account erstellt hat: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal für einen Abend so getan hat, als würde er/sie jemanden nicht kennen: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal jemanden am selben Tag kennengelernt und geküsst hat: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal auf ein Date gewartet, das nicht aufgetaucht ist: 3 Schlücke.", category: "spicy" },
  { text: "Wer schon mal jemanden angeschrieben hat, nur weil sein/ihr Song auf Spotify lief: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal beim Ausgehen den Abend mit jemand anderem als geplant verbracht hat: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal eine Fernbeziehung geführt hat: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal jemandem über eine lange Zeit Gefühle verschwiegen hat: 2 Schlücke.", category: "spicy" },
  { text: "Wer schon mal etwas getan hat, das ihn/sie besser schlafen ließ – auch wenn es nicht richtig war: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal gemerkt hat, dass er/sie eine andere Person mehr brauchte als gedacht: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal eine Beziehung weitergezogen hat, weil er/sie zu müde war, Schluss zu machen: 3 Schlücke.", category: "deep" },
  { text: "Wer schon mal jemanden so sehr vermisst hat, dass er/sie ihn/sie fast angeschrieben hätte: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal bereut hat, nicht früher Nein gesagt zu haben: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal geweint hat und dabei gelacht hat – gleichzeitig: 1 Schluck.", category: "deep" },
  { text: "Wer schon mal für eine Person alles gewesen ist und gleichzeitig nichts: 3 Schlücke.", category: "deep" },
  { text: "Wer schon mal jemanden geliebt hat, ohne dass diese Person von seiner/ihrer Existenz wusste: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal etwas getan hat, das er/sie nur für sich selbst getan hat – ohne irgendwen einzuweihen: 1 Schluck.", category: "deep" },
  { text: "Wer schon mal durch eine Krise gewachsen ist – und es erst danach bemerkt hat: 1 Schluck.", category: "deep" },
  { text: "Wer schon mal so erschöpft war, dass er/sie nichts mehr gefühlt hat: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal jemanden aus Gewohnheit vermisst hat statt wirklich: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal ein Gespräch so oft im Kopf durchgespielt hat, dass er/sie es nie geführt hat: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal für sich selbst entschieden hat – gegen den Rat aller anderen: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal jemandem erlaubt hat, zu nah zu kommen, und es bereut hat: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal so lange stark gewesen ist, dass er/sie vergessen hat, schwach sein zu dürfen: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal einem fremden Menschen etwas anvertraut hat, was seine/ihre Nächsten nicht wissen: 3 Schlücke.", category: "deep" },
  { text: "Wer schon mal bewusst aufgehört hat, sich zu bemühen – und es hat sich gut angefühlt: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal einen Brief angefangen hat und nie abgeschickt hat: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal jemanden so sehr vermisst hat, dass er/sie alte Nachrichten gelesen hat: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal in einer Freundschaft mehr gegeben hat als genommen: 1 Schluck.", category: "deep" },
  { text: "Wer schon mal etwas für sich behalten hat, das ihn/sie noch heute beschäftigt: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal jemanden in Schutz genommen hat, der/die es nicht verdient hatte: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal aufgehört hat, sich zu entschuldigen, und befreit war: 1 Schluck.", category: "deep" },
  { text: "Wer schon mal jemanden um Erlaubnis gebeten hat, obwohl er/sie sie nicht brauchte: 1 Schluck.", category: "deep" },
  { text: "Wer schon mal etwas festgehalten hat, weil loslassen sich unmöglich anfühlte: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal gemerkt hat, dass er/sie jemanden unabsichtlich verletzt hat: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal in einen Raum voller Menschen gefühlt hat, ganz allein zu sein: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal jemanden gebeten hat, zu bleiben – und er/sie ist gegangen: 3 Schlücke.", category: "deep" },
  { text: "Wer schon mal merkte, dass er/sie nicht traurig war wegen jemandes, sondern wegen der Idee von ihm/ihr: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal jemanden enttäuscht hat, der/die ihm/ihr vertraut hat: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal einen Freund oder eine Freundin um Rat gebeten und das Gegenteil gemacht hat: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal jemanden für seinen Mut bewundert hat und sich selbst dafür geschämt hat, ihn nicht zu haben: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal etwas Schönes kaputtgemacht hat, weil er/sie Angst vor dem Verlieren hatte: 3 Schlücke.", category: "deep" },
  { text: "Wer schon mal jemanden gebraucht hat, der nicht da war: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal so sehr in etwas investiert hat, dass er/sie nicht aufhören konnte – obwohl er/sie wusste, es ist falsch: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal wegen eines Traums so glücklich war, dass er/sie traurig war, als er aufwachte: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal jemandem die Schuld gegeben hat für etwas, das er/sie selbst mitverursacht hat: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal jemanden mehr vermisst hat als erwartet: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal erkannt hat, wer wirklich da ist – in einer Krise: 1 Schluck.", category: "deep" },
  { text: "Wer schon mal so getan hat, als würde es ihm/ihr gut gehen – monatelang: 3 Schlücke.", category: "deep" },
  { text: "Wer schon mal jemanden vermisst hat, obwohl er/sie weiß, es war besser so: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal einen Teil von sich zurückgelassen hat, als er/sie jemanden verlassen hat: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal Angst davor hatte, glücklich zu sein: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal jemandem mehr geglaubt hat als sich selbst: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal jemanden geliebt hat, der/die kein Gutes in sich sehen konnte: 3 Schlücke.", category: "deep" },
  { text: "Wer schon mal erkannt hat, dass manche Menschen saisonal in unser Leben treten – und es akzeptiert: 1 Schluck.", category: "deep" },
  { text: "Wer schon mal sich selbst mehr Schaden zugefügt hat als irgendein anderer: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal ein Wiedersehen so sehnlich herbeigewünscht hat, dass er/sie enttäuscht war, wenn es passierte: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal jemandem in einer schlechten Zeit beigestanden hat, obwohl er/sie selbst Hilfe brauchte: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal eine schöne Erinnerung an jemanden hat, den er/sie nie wiedersehen wird: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal etwas Wichtiges gesagt hat – zu spät: 3 Schlücke.", category: "deep" },
  { text: "Wer schon mal erkannt hat, was er/sie wirklich will – und Angst bekam: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal jemanden so tief angeschaut hat, dass es ihm/ihr peinlich war: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal jemandem dankbar war für etwas Unausgesprochenes: 1 Schluck.", category: "deep" },
  { text: "Wer schon mal spürte, dass jemand ihn/sie wirklich versteht – ohne Worte: 1 Schluck.", category: "deep" },
  { text: "Wer schon mal so getan hat als ob er/sie nicht vermisst wird – obwohl er/sie hoffte, vermisst zu werden: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal eine Wahl getroffen hat, die ihn/sie zu einer anderen Person gemacht hat: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal einen Fehler wiederholt hat, weil er/sie wusste wie er endet – und es wollte: 3 Schlücke.", category: "deep" },
  { text: "Wer schon mal erkannt hat, dass er/sie die falsche Person festgehalten hat: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal Stunden lang über eine Nachricht nachgedacht hat, die er/sie nie geschrieben hat: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal etwas Schmerzhaftes als Wachstum erkannt hat – erst im Nachhinein: 1 Schluck.", category: "deep" },
  { text: "Wer schon mal jemandem gezeigt hat, wie verletzlich er/sie ist – und es wurde nicht ausgenutzt: 1 Schluck.", category: "deep" },
  { text: "Wer schon mal etwas Falsches getan hat, weil die richtige Sache zu schmerzhaft war: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal erkannt hat, dass er/sie nicht gut genug war – und sich dafür geschämt hat: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal gemerkt hat, dass er/sie jemanden braucht, aber nicht wusste wie darum bitten: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal eine Freundschaft höher geschätzt hat als eine romantische Beziehung: 1 Schluck.", category: "deep" },
  { text: "Wer schon mal jemandem zugehört hat, ohne zu urteilen – und es war schwer: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal etwas verloren hat, das er/sie für selbstverständlich hielt: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal so wütend war, dass er/sie nichts gesagt hat – und es war die richtige Entscheidung: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal jemandem vergeben hat, ohne eine Entschuldigung zu bekommen: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal erkannt hat, wie viel Raum jemand im eigenen Kopf einnimmt – obwohl er/sie schon längst weg ist: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal so getan hat als wäre es ok – lange – bis es nicht mehr ok war: 3 Schlücke.", category: "deep" },
  { text: "Wer schon mal jemanden aufgegeben hat, weil er/sie keine Kraft mehr hatte: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal so sehr aus seiner Komfortzone herausgetreten ist, dass er/sie sich nicht mehr wiederkannte: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal jemanden um einen Gefallen gebeten hat – und er/sie bat nie wieder: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal etwas Persönliches in einem Lied wiedererkannt hat: 1 Schluck.", category: "deep" },
  { text: "Wer schon mal jemanden zurückgewonnen hat, den er/sie fast verloren hatte: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal jemanden so sehr geliebt hat, dass es ihn/sie erschreckte: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal erkannt hat, dass Schweigen manchmal die lauteste Aussage ist: 1 Schluck.", category: "deep" },
  { text: "Wer schon mal mehr Energie in das Ende einer Sache gesteckt hat als in den Anfang: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal so lange gewartet hat, dass die Sache sich von selbst erledigt hat: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal jemandem die Wahrheit gesagt hat, obwohl er/sie wusste, sie verliert ihn/sie dadurch: 3 Schlücke.", category: "deep" },
  { text: "Wer schon mal erkannt hat, wann er/sie der Grund für den Schmerz eines anderen war: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal jemanden mehr geliebt hat als sich selbst: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal etwas getan hat, nur um bemerkt zu werden: 1 Schluck.", category: "deep" },
  { text: "Wer schon mal tiefer in jemanden verliebt war als er/sie zugeben wollte: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal denjenigen um Rat gebeten hat, über den er/sie sprach: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal erkannt hat, dass er/sie manche Menschen festgehalten hat, die schon lange losgelassen hatten: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal für jemanden stark gewesen ist, den er/sie gerade am nötigsten brauchte: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal mitten in einer Nacht allein spazieren war – nicht aus Spaß: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal etwas Wichtiges verschwiegen hat, um jemanden zu schützen – und es hat funktioniert: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal erkannt hat, dass Veränderung kein Verrat ist: 1 Schluck.", category: "deep" },
  { text: "Wer schon mal für jemanden ein anderer Mensch sein wollte: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal aufgehört hat, sich zu verstecken – und es war der wichtigste Schritt: 1 Schluck.", category: "deep" },
  { text: "Wer schon mal merkte, wie viel Raum alte Wunden noch einnehmen: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal so viel Angst vor dem Verlieren hatte, dass er/sie nicht mehr genießen konnte: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal jemanden losgelassen hat, dem er/sie noch hinterherlief: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal mehr Kraft hatte, als er/sie dachte – und sich das erst in der Krise gezeigt hat: 1 Schluck.", category: "deep" },
  { text: "Wer schon mal erkannt hat, dass manche Dinge ohne Erklärung enden müssen: 2 Schlücke.", category: "deep" },
  { text: "Wer schon mal aufgehört hat, sich zu rechtfertigen – und es hat sich wie Freiheit angefühlt: 1 Schluck.", category: "deep" },
];
